import type { Difficulty } from "@/types";

export interface DialogueScenario {
  id: number;
  title: string;
  topic: string;
  difficulty: Difficulty;
  lines: DialogueLine[];
}

export interface DialogueLine {
  speaker: "A" | "B";
  text: string;
  correctAnswer: string;
  options: string[];
  explanation: string;
}

export const dialogueScenarios: DialogueScenario[] = [
  // === BEGINNER SCENARIOS (7) ===
  {
    id: 1,
    title: "Заказ в ресторане",
    topic: "restaurant",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "Hello! Can I ___ the menu, please?",
        correctAnswer: "see",
        options: ["see", "look", "watch", "find"],
        explanation: "\"See\" используется для получения визуальной информации. \"Can I see the menu?\" — стандартная фраза в ресторане.",
      },
      {
        speaker: "B",
        text: "Of course. ___ you like something to drink first?",
        correctAnswer: "Would",
        options: ["Would", "Could", "Should", "Must"],
        explanation: "\"Would you like\" — вежливая форма предложения, используется в сфере обслуживания.",
      },
      {
        speaker: "A",
        text: "Yes, I'd like a ___ of water, please.",
        correctAnswer: "glass",
        options: ["glass", "cup", "bottle", "plate"],
        explanation: "\"A glass of water\" — правильное выражение для воды в стакане. \"Cup\" обычно для горячих напитков.",
      },
      {
        speaker: "B",
        text: "Here you go. Are you ___ to order now?",
        correctAnswer: "ready",
        options: ["ready", "prepared", "happy", "able"],
        explanation: "\"Are you ready to order?\" — стандартный вопрос официанта о готовности сделать заказ.",
      },
      {
        speaker: "A",
        text: "Yes, I'll have the grilled chicken, please. That ___ delicious.",
        correctAnswer: "sounds",
        options: ["sounds", "hears", "tastes", "smells"],
        explanation: "\"That sounds delicious\" — выражает реакцию на услышанное описание блюда.",
      },
    ],
  },
  {
    id: 2,
    title: "Регистрация в аэропорту",
    topic: "airport",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "Good morning! Can I see your ___ and ticket, please?",
        correctAnswer: "passport",
        options: ["passport", "wallet", "card", "document"],
        explanation: "\"Passport\" — загранпаспорт, основной документ для международных перелётов.",
      },
      {
        speaker: "B",
        text: "Here you are. I'm ___ to London today.",
        correctAnswer: "flying",
        options: ["flying", "going", "leaving", "taking"],
        explanation: "\"I'm flying to\" используется, когда речь идёт о путешествии на самолёте.",
      },
      {
        speaker: "A",
        text: "Do you have any ___ to check in?",
        correctAnswer: "luggage",
        options: ["luggage", "baggage", "suitcase", "bags"],
        explanation: "\"Luggage\" и \"baggage\" — синонимы, оба означают \"багаж\". В аэропортах часто используют \"luggage\".",
      },
      {
        speaker: "B",
        text: "Just one suitcase. What's the ___ for hand luggage?",
        correctAnswer: "limit",
        options: ["limit", "size", "weight", "number"],
        explanation: "\"Weight limit\" или просто \"limit\" — ограничение по весу для ручной клади.",
      },
      {
        speaker: "A",
        text: "Seven kilograms. Here's your boarding pass. The gate ___ at 10:30.",
        correctAnswer: "closes",
        options: ["closes", "opens", "starts", "ends"],
        explanation: "\"The gate closes\" — посадка заканчивается в указанное время.",
      },
    ],
  },
  {
    id: 3,
    title: "Магазин: покупка одежды",
    topic: "shopping",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "Excuse me, how ___ does this shirt cost?",
        correctAnswer: "much",
        options: ["much", "many", "long", "big"],
        explanation: "\"How much\" используется с неисчисляемыми существительными, включая деньги и цены.",
      },
      {
        speaker: "B",
        text: "It's $25. Would you like to try it ___?",
        correctAnswer: "on",
        options: ["on", "out", "in", "up"],
        explanation: "\"Try it on\" — фразовый глагол, означающий «примерить одежду».",
      },
      {
        speaker: "A",
        text: "Yes, where are the ___ rooms?",
        correctAnswer: "fitting",
        options: ["fitting", "changing", "dressing", "trying"],
        explanation: "\"Fitting room\" — примерочная. Также говорят \"changing room\".",
      },
      {
        speaker: "B",
        text: "Just over there. What ___ do you need?",
        correctAnswer: "size",
        options: ["size", "color", "style", "number"],
        explanation: "\"What size?\" — стандартный вопрос продавца о размере одежды.",
      },
    ],
  },
  {
    id: 4,
    title: "У врача",
    topic: "doctor",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "What seems to be the ___?",
        correctAnswer: "problem",
        options: ["problem", "trouble", "issue", "matter"],
        explanation: "\"What seems to be the problem?\" — стандартный вопрос врача о симптомах.",
      },
      {
        speaker: "B",
        text: "I have a bad ___ and a sore throat.",
        correctAnswer: "headache",
        options: ["headache", "stomachache", "toothache", "backache"],
        explanation: "\"Headache\" — головная боль. \"Sore throat\" — больное горло.",
      },
      {
        speaker: "A",
        text: "Let me check your ___. Open your mouth, please.",
        correctAnswer: "temperature",
        options: ["temperature", "pressure", "heart", "eyes"],
        explanation: "\"Check your temperature\" — измерить температуру. Стандартная процедура осмотра.",
      },
      {
        speaker: "A",
        text: "You should ___ some medicine and rest for a few days.",
        correctAnswer: "take",
        options: ["take", "eat", "drink", "make"],
        explanation: "\"Take medicine\" — принимать лекарство. Устойчивое выражение.",
      },
    ],
  },
  {
    id: 5,
    title: "Указание направления",
    topic: "directions",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "Excuse me, could you ___ me how to get to the museum?",
        correctAnswer: "tell",
        options: ["tell", "say", "speak", "explain"],
        explanation: "\"Could you tell me\" — вежливая просьба объяснить дорогу. \"Tell\" требует косвенного дополнения.",
      },
      {
        speaker: "B",
        text: "Sure. Go straight and ___ left at the traffic lights.",
        correctAnswer: "turn",
        options: ["turn", "take", "make", "get"],
        explanation: "\"Turn left/right\" — повернуть налево/направо. Стандартное указание направления.",
      },
      {
        speaker: "A",
        text: "How ___ will it take to walk there?",
        correctAnswer: "long",
        options: ["long", "far", "much", "many"],
        explanation: "\"How long\" — вопрос о продолжительности. \"How far\" — о расстоянии.",
      },
      {
        speaker: "B",
        text: "About ten minutes. You can't ___ it, it's a big building.",
        correctAnswer: "miss",
        options: ["miss", "lose", "forget", "leave"],
        explanation: "\"You can't miss it\" — устойчивая фраза, означающая «вы не пропустите, здание заметное».",
      },
    ],
  },
  {
    id: 6,
    title: "Светская беседа",
    topic: "small-talk",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "Nice weather we're ___ today, isn't it?",
        correctAnswer: "having",
        options: ["having", "making", "doing", "getting"],
        explanation: "\"We're having\" используется для описания текущей погоды. Present Continuous.",
      },
      {
        speaker: "B",
        text: "Yes, it's beautiful! What do you ___ for a living?",
        correctAnswer: "do",
        options: ["do", "work", "make", "have"],
        explanation: "\"What do you do for a living?\" — вежливый вопрос о профессии.",
      },
      {
        speaker: "A",
        text: "I'm a teacher. I ___ English at a local school.",
        correctAnswer: "teach",
        options: ["teach", "learn", "study", "know"],
        explanation: "\"Teach\" — обучать. \"I teach English\" означает «я преподаю английский».",
      },
      {
        speaker: "B",
        text: "That ___ interesting! Do you enjoy it?",
        correctAnswer: "sounds",
        options: ["sounds", "hears", "looks", "feels"],
        explanation: "\"That sounds interesting\" — выражение заинтересованности в разговоре.",
      },
    ],
  },
  {
    id: 7,
    title: "Заселение в отель",
    topic: "hotel",
    difficulty: "beginner",
    lines: [
      {
        speaker: "A",
        text: "Good evening. I have a ___ under the name Smith.",
        correctAnswer: "reservation",
        options: ["reservation", "booking", "room", "stay"],
        explanation: "\"I have a reservation\" — стандартная фраза при заселении в отель. \"Booking\" — синоним.",
      },
      {
        speaker: "B",
        text: "Let me ___ that for you. Yes, a single room for three nights.",
        correctAnswer: "check",
        options: ["check", "find", "look", "search"],
        explanation: "\"Let me check\" — разрешите проверить. \"Check\" здесь означает «проверить информацию».",
      },
      {
        speaker: "A",
        text: "What time is ___ served?",
        correctAnswer: "breakfast",
        options: ["breakfast", "dinner", "lunch", "food"],
        explanation: "\"Breakfast is served\" — завтрак подаётся. Вопрос о времени завтрака.",
      },
      {
        speaker: "B",
        text: "From 7 to 10. Here's your key card. Enjoy your ___.",
        correctAnswer: "stay",
        options: ["stay", "visit", "time", "room"],
        explanation: "\"Enjoy your stay\" — наслаждайтесь вашим пребыванием. Стандартная фраза в отелях.",
      },
    ],
  },

  // === INTERMEDIATE SCENARIOS (7) ===
  {
    id: 8,
    title: "Собеседование на работу",
    topic: "job-interview",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "Could you walk me ___ your professional experience?",
        correctAnswer: "through",
        options: ["through", "over", "into", "across"],
        explanation: "\"Walk me through\" — фразовый глагол, означающий «расскажите подробно о чём-то».",
      },
      {
        speaker: "B",
        text: "Certainly. I've been working in marketing ___ over five years.",
        correctAnswer: "for",
        options: ["for", "since", "during", "while"],
        explanation: "\"For\" используется с duration (периодом времени). \"Since\" — с конкретной датой.",
      },
      {
        speaker: "A",
        text: "How do you handle working under ___?",
        correctAnswer: "pressure",
        options: ["pressure", "stress", "deadline", "burden"],
        explanation: "\"Work under pressure\" — работать в условиях стресса. Распространённый вопрос на собеседовании.",
      },
      {
        speaker: "B",
        text: "I prioritize tasks and stay ___. I find it motivating.",
        correctAnswer: "focused",
        options: ["focused", "fixed", "attached", "connected"],
        explanation: "\"Stay focused\" — оставаться сосредоточенным. Важное качество для работодателя.",
      },
      {
        speaker: "A",
        text: "Where do you see yourself in five years' ___?",
        correctAnswer: "time",
        options: ["time", "period", "space", "age"],
        explanation: "\"In five years' time\" — устойчивое выражение о будущем через пять лет.",
      },
    ],
  },
  {
    id: 9,
    title: "Телефонный разговор",
    topic: "phone-call",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "Hello, could I ___ to Mr. Johnson, please?",
        correctAnswer: "speak",
        options: ["speak", "talk", "tell", "say"],
        explanation: "\"Could I speak to\" — вежливая форма запроса телефонного соединения.",
      },
      {
        speaker: "B",
        text: "I'm afraid he's not ___ at the moment. Can I take a message?",
        correctAnswer: "available",
        options: ["available", "free", "ready", "present"],
        explanation: "\"Not available\" — стандартный ответ секретаря, когда человек занят или отсутствует.",
      },
      {
        speaker: "A",
        text: "Yes, could you ask him to call me ___ as soon as possible?",
        correctAnswer: "back",
        options: ["back", "again", "return", "later"],
        explanation: "\"Call me back\" — перезвонить. Фразовый глагол с обязательным дополнением.",
      },
      {
        speaker: "B",
        text: "Of course. Can I ___ your name again?",
        correctAnswer: "have",
        options: ["have", "get", "take", "know"],
        explanation: "\"Can I have your name?\" — вежливая просьба повторить имя. Более формально, чем \"What's your name?\".",
      },
      {
        speaker: "A",
        text: "It's Sarah Thompson. Thanks for your ___, I'll wait for his call.",
        correctAnswer: "help",
        options: ["help", "time", "effort", "work"],
        explanation: "\"Thanks for your help\" — стандартное вежливое завершение телефонного разговора.",
      },
    ],
  },
  {
    id: 10,
    title: "Деловая встреча",
    topic: "business-meeting",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "Let's get ___ to business. The first item on the agenda is the quarterly report.",
        correctAnswer: "down",
        options: ["down", "up", "on", "off"],
        explanation: "\"Get down to business\" — идиома, означающая «приступить к делу, перейти к сути».",
      },
      {
        speaker: "B",
        text: "I'd like to ___ out that our sales have increased by 15%.",
        correctAnswer: "point",
        options: ["point", "make", "bring", "show"],
        explanation: "\"Point out\" — указывать, обращать внимание. Важный фразовый глагол для презентаций.",
      },
      {
        speaker: "A",
        text: "That's impressive. How do you ___ for the next quarter?",
        correctAnswer: "account",
        options: ["account", "explain", "answer", "reason"],
        explanation: "\"Account for\" — объяснять причину. Используется в деловом контексте.",
      },
      {
        speaker: "B",
        text: "We expect to ___ even better results with our new strategy.",
        correctAnswer: "achieve",
        options: ["achieve", "reach", "arrive", "make"],
        explanation: "\"Achieve results\" — достигать результатов. Более формально, чем \"get results\".",
      },
      {
        speaker: "A",
        text: "Let's ___ this offline after the meeting to discuss the details.",
        correctAnswer: "take",
        options: ["take", "bring", "leave", "move"],
        explanation: "\"Take this offline\" — деловая идиома, означающая «обсудить отдельно/после встречи».",
      },
    ],
  },
  {
    id: 11,
    title: "Извинение и примирение",
    topic: "apologizing",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "I need to ___ for missing our appointment yesterday. I completely forgot.",
        correctAnswer: "apologize",
        options: ["apologize", "excuse", "regret", "pardon"],
        explanation: "\"Apologize for\" — извиняться за что-либо. Более формально, чем \"sorry\".",
      },
      {
        speaker: "B",
        text: "I was quite upset, to be ___. I waited for over an hour.",
        correctAnswer: "honest",
        options: ["honest", "frank", "true", "real"],
        explanation: "\"To be honest\" — честно говоря. Выражает искренность в разговоре.",
      },
      {
        speaker: "A",
        text: "I know, and I feel ___ about it. It won't happen again.",
        correctAnswer: "terrible",
        options: ["terrible", "badly", "poorly", "wrong"],
        explanation: "\"I feel terrible\" — я ужасно себя чувствую. Выражение глубокого сожаления.",
      },
      {
        speaker: "B",
        text: "Alright. Let's ___ it behind us and move on.",
        correctAnswer: "put",
        options: ["put", "leave", "set", "get"],
        explanation: "\"Put it behind us\" — оставить в прошлом. Идиома для примирения.",
      },
    ],
  },
  {
    id: 12,
    title: "Выражение мнения",
    topic: "expressing-opinion",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "What's your ___ on the new company policy about remote work?",
        correctAnswer: "opinion",
        options: ["opinion", "thought", "idea", "view"],
        explanation: "\"Take on\" или \"opinion on\" — мнение о чём-либо. Более продвинутая альтернатива \"think about\".",
      },
      {
        speaker: "B",
        text: "To be ___, I think it's a step in the right direction.",
        correctAnswer: "frank",
        options: ["frank", "true", "real", "clear"],
        explanation: "\"To be frank\" — откровенно говоря. Формальный способ выразить мнение.",
      },
      {
        speaker: "A",
        text: "I see your point, but I'd ___ to disagree about the schedule.",
        correctAnswer: "beg",
        options: ["beg", "ask", "want", "tend"],
        explanation: "\"I beg to differ\" — вежливая форма несогласия. Идиоматическое выражение.",
      },
      {
        speaker: "B",
        text: "Fair enough. Let's agree to ___.",
        correctAnswer: "disagree",
        options: ["disagree", "differ", "dispute", "argue"],
        explanation: "\"Agree to disagree\" — согласиться на разные мнения. Идиома для мирного завершения спора.",
      },
    ],
  },
  {
    id: 13,
    title: "Планирование встречи",
    topic: "making-plans",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "Are you ___ to do anything this weekend?",
        correctAnswer: "planning",
        options: ["planning", "thinking", "wanting", "hoping"],
        explanation: "\"Are you planning to\" — планируешь ли ты. Present Continuous для будущих планов.",
      },
      {
        speaker: "B",
        text: "I was thinking of ___ a hike if the weather's nice.",
        correctAnswer: "going",
        options: ["going", "making", "taking", "doing"],
        explanation: "\"Going for a hike\" — пойти в поход. \"Thinking of + -ing\" — размышлять о.",
      },
      {
        speaker: "A",
        text: "That sounds great! Would you ___ if I joined you?",
        correctAnswer: "mind",
        options: ["mind", "like", "want", "allow"],
        explanation: "\"Would you mind if\" — вежливый вопрос о разрешении присоединиться.",
      },
      {
        speaker: "B",
        text: "Not at all! The more, the ___.",
        correctAnswer: "merrier",
        options: ["merrier", "better", "happier", "nicer"],
        explanation: "\"The more, the merrier\" — идиома: чем больше людей, тем веселее.",
      },
    ],
  },
  {
    id: 14,
    title: "Просьба о помощи",
    topic: "asking-for-help",
    difficulty: "intermediate",
    lines: [
      {
        speaker: "A",
        text: "I'm really struggling with this report. Would you mind giving me a ___?",
        correctAnswer: "hand",
        options: ["hand", "help", "favor", "lift"],
        explanation: "\"Give me a hand\" — помочь. Неформальная идиома для просьбы о помощи.",
      },
      {
        speaker: "B",
        text: "Of course! I'd be happy to ___. What seems to be the issue?",
        correctAnswer: "help",
        options: ["help", "assist", "support", "aid"],
        explanation: "\"I'd be happy to help\" — я с радостью помогу. Вежливый и дружелюбный ответ.",
      },
      {
        speaker: "A",
        text: "I can't figure ___ how to format the data tables.",
        correctAnswer: "out",
        options: ["out", "up", "on", "in"],
        explanation: "\"Figure out\" — понять, разобраться. Фразовый глагол для решения проблем.",
      },
      {
        speaker: "B",
        text: "Let me show you. It's actually quite ___ once you know how.",
        correctAnswer: "straightforward",
        options: ["straightforward", "easy", "simple", "clear"],
        explanation: "\"Straightforward\" — простой, понятный. Более продвинутый синоним \"easy\".",
      },
    ],
  },

  // === ADVANCED SCENARIOS (6) ===
  {
    id: 15,
    title: "Переговоры о зарплате",
    topic: "negotiation",
    difficulty: "advanced",
    lines: [
      {
        speaker: "A",
        text: "I believe my contributions have ___ expectations this past year.",
        correctAnswer: "exceeded",
        options: ["exceeded", "overcome", "surpassed", "transcended"],
        explanation: "\"Exceed expectations\" — превзойти ожидания. Ключевая фраза для переговоров о повышении.",
      },
      {
        speaker: "B",
        text: "We acknowledge your performance. What compensation were you ___ in mind?",
        correctAnswer: "bearing",
        options: ["bearing", "keeping", "holding", "having"],
        explanation: "\"Bear in mind\" — иметь в виду. Более формальная альтернатива \"thinking of\".",
      },
      {
        speaker: "A",
        text: "Given my track record, a 15% raise would be ___ with industry standards.",
        correctAnswer: "commensurate",
        options: ["commensurate", "comparable", "equivalent", "matching"],
        explanation: "\"Commensurate with\" — соответствовать, быть соразмерным. Продвинутая деловая лексика.",
      },
      {
        speaker: "B",
        text: "That's a bit higher than we had ___. Could we meet in the middle at 10%?",
        correctAnswer: "anticipated",
        options: ["anticipated", "expected", "predicted", "forecast"],
        explanation: "\"Had anticipated\" — предполагали. Past Perfect для вежливого смягчения отказа.",
      },
      {
        speaker: "A",
        text: "I can ___ with 10% provided we revisit this in six months.",
        correctAnswer: "work",
        options: ["work", "deal", "live", "manage"],
        explanation: "\"I can work with that\" — меня это устраивает. Деловая идиома для компромисса.",
      },
      {
        speaker: "B",
        text: "Agreed. We'll ___ your performance review forward to December.",
        correctAnswer: "bring",
        options: ["bring", "push", "move", "pull"],
        explanation: "\"Bring forward\" — перенести на более ранний срок. Фразовый глагол в деловом контексте.",
      },
    ],
  },
  {
    id: 16,
    title: "Академическая дискуссия",
    topic: "academic-discussion",
    difficulty: "advanced",
    lines: [
      {
        speaker: "A",
        text: "I'd like to ___ the hypothesis that language shapes thought.",
        correctAnswer: "challenge",
        options: ["challenge", "argue", "dispute", "contest"],
        explanation: "\"Challenge a hypothesis\" — оспаривать гипотезу. Академическая лексика.",
      },
      {
        speaker: "B",
        text: "That's an intriguing ___. However, empirical evidence suggests otherwise.",
        correctAnswer: "proposition",
        options: ["proposition", "suggestion", "idea", "view"],
        explanation: "\"Intriguing proposition\" — интересное предположение. Формальный академический стиль.",
      },
      {
        speaker: "A",
        text: "I'd argue the methodology used in those studies is somewhat ___.",
        correctAnswer: "flawed",
        options: ["flawed", "broken", "wrong", "failed"],
        explanation: "\"Methodology is flawed\" — методология имеет недостатки. Научный язык дискуссии.",
      },
      {
        speaker: "B",
        text: "Perhaps we should ___ a more nuanced approach to this analysis.",
        correctAnswer: "adopt",
        options: ["adopt", "take", "choose", "pick"],
        explanation: "\"Adopt an approach\" — принять подход. Более формально, чем \"take\".",
      },
      {
        speaker: "A",
        text: "I concur. The ___ between linguistic and cognitive factors requires deeper exploration.",
        correctAnswer: "interplay",
        options: ["interplay", "connection", "link", "relation"],
        explanation: "\"Interplay\" — взаимодействие. Продвинутое слово для описания сложных взаимосвязей.",
      },
    ],
  },
  {
    id: 17,
    title: "Жалоба клиента",
    topic: "customer-complaint",
    difficulty: "advanced",
    lines: [
      {
        speaker: "A",
        text: "I'm writing to express my ___ with the service I received last Tuesday.",
        correctAnswer: "dissatisfaction",
        options: ["dissatisfaction", "displeasure", "disappointment", "unhappiness"],
        explanation: "\"Express dissatisfaction\" — выразить недовольство. Стандартное начало официальной жалобы.",
      },
      {
        speaker: "B",
        text: "I sincerely apologize for the ___. Could you elaborate on what went wrong?",
        correctAnswer: "inconvenience",
        options: ["inconvenience", "trouble", "problem", "issue"],
        explanation: "\"Apologize for the inconvenience\" — извиниться за неудобства. Формальная клиентская лексика.",
      },
      {
        speaker: "A",
        text: "The delivery was ___ by two weeks, and the product arrived damaged.",
        correctAnswer: "delayed",
        options: ["delayed", "postponed", "extended", "stalled"],
        explanation: "\"Delayed by\" — задержано на. Используется с указанием периода задержки.",
      },
      {
        speaker: "B",
        text: "This is indeed ___. I'll escalate this to our quality assurance team immediately.",
        correctAnswer: "unacceptable",
        options: ["unacceptable", "intolerable", "terrible", "dreadful"],
        explanation: "\"Unacceptable\" — неприемлемо. Вежливый, но твёрдый способ признать ошибку компании.",
      },
      {
        speaker: "A",
        text: "I'd appreciate it if you could ___ this matter as a priority.",
        correctAnswer: "resolve",
        options: ["resolve", "solve", "fix", "handle"],
        explanation: "\"Resolve a matter\" — урегулировать вопрос. Более формально, чем \"fix\".",
      },
      {
        speaker: "B",
        text: "Absolutely. We'll dispatch a replacement forthwith and include a voucher as ___ for your trouble.",
        correctAnswer: "compensation",
        options: ["compensation", "payment", "reward", "refund"],
        explanation: "\"As compensation\" — в качестве компенсации. Профессиональный подход к работе с жалобами.",
      },
    ],
  },
  {
    id: 18,
    title: "Бронирование столика",
    topic: "making-reservation",
    difficulty: "advanced",
    lines: [
      {
        speaker: "A",
        text: "I'd like to make a reservation for dinner this ___.",
        correctAnswer: "Saturday",
        options: ["Saturday", "Friday", "Sunday", "Thursday"],
        explanation: "Контекст: бронирование столика на ужин в выходной день.",
      },
      {
        speaker: "B",
        text: "Certainly. How many people will be in your ___?",
        correctAnswer: "party",
        options: ["party", "group", "team", "family"],
        explanation: "\"Party\" в ресторанном контексте означает «компания гостей», не «вечеринка».",
      },
      {
        speaker: "A",
        text: "A table for four, please. Preferably by the ___.",
        correctAnswer: "window",
        options: ["window", "door", "kitchen", "bar"],
        explanation: "\"By the window\" — у окна. Частый запрос при бронировании столика.",
      },
      {
        speaker: "B",
        text: "I'll do my best to ___ that. Could I have a contact number?",
        correctAnswer: "accommodate",
        options: ["accommodate", "satisfy", "fulfill", "complete"],
        explanation: "\"Accommodate\" — удовлетворить запрос. Профессиональная лексика обслуживания.",
      },
      {
        speaker: "A",
        text: "Yes, it's 555-0123. Do you have any ___ requirements?",
        correctAnswer: "dietary",
        options: ["dietary", "food", "eating", "menu"],
        explanation: "\"Dietary requirements\" — диетические требования. Важный вопрос в хороших ресторанах.",
      },
    ],
  },
  {
    id: 19,
    title: "Неформальная беседа с друзьями",
    topic: "casual-chat",
    difficulty: "advanced",
    lines: [
      {
        speaker: "A",
        text: "Long time no see! How have you been ___ up?",
        correctAnswer: "keeping",
        options: ["keeping", "holding", "staying", "getting"],
        explanation: "\"How have you been keeping?\" — неформальный вопрос о жизни и делах.",
      },
      {
        speaker: "B",
        text: "Can't ___. Work's been insane, but otherwise I'm doing alright.",
        correctAnswer: "complain",
        options: ["complain", "argue", "protest", "object"],
        explanation: "\"Can't complain\" — грех жаловаться. Разговорная идиома.",
      },
      {
        speaker: "A",
        text: "I hear you. We should definitely ___ up soon. It's been ages.",
        correctAnswer: "catch",
        options: ["catch", "meet", "hang", "pick"],
        explanation: "\"Catch up\" — встретиться и поделиться новостями. Разговорный фразовый глагол.",
      },
      {
        speaker: "B",
        text: "For sure! Let's not leave it ___ long next time.",
        correctAnswer: "that",
        options: ["that", "so", "too", "this"],
        explanation: "\"Leave it that long\" — откладывать настолько надолго. Разговорная конструкция.",
      },
      {
        speaker: "A",
        text: "Deal. By the way, you'll never ___ what happened at work yesterday.",
        correctAnswer: "guess",
        options: ["guess", "know", "believe", "imagine"],
        explanation: "\"You'll never guess\" — ни за что не угадаешь. Способ начать интересную историю.",
      },
    ],
  },
  {
    id: 20,
    title: "Бизнес-презентация",
    topic: "presentation",
    difficulty: "advanced",
    lines: [
      {
        speaker: "A",
        text: "Good morning, everyone. Thank you for ___ the time to attend today's presentation.",
        correctAnswer: "taking",
        options: ["taking", "making", "giving", "spending"],
        explanation: "\"Thank you for taking the time\" — спасибо, что нашли время. Стандартное вступительное обращение.",
      },
      {
        speaker: "A",
        text: "I'll ___ you through our quarterly performance before we open the floor for questions.",
        correctAnswer: "walk",
        options: ["walk", "take", "guide", "lead"],
        explanation: "\"Walk you through\" — провести вас по. Фразовый глагол для структурированной презентации.",
      },
      {
        speaker: "A",
        text: "As you can see from the slide, our market share has grown ___.",
        correctAnswer: "exponentially",
        options: ["exponentially", "dramatically", "sharply", "rapidly"],
        explanation: "\"Exponentially\" — экспоненциально. Продвинутая бизнес-лексика для впечатляющего роста.",
      },
      {
        speaker: "B",
        text: "That's impressive. Could you elaborate on the ___ behind this growth?",
        correctAnswer: "drivers",
        options: ["drivers", "reasons", "causes", "factors"],
        explanation: "\"Drivers\" — движущие силы. Бизнес-термин для ключевых факторов.",
      },
      {
        speaker: "A",
        text: "Certainly. The primary ___ have been our expansion into Asian markets and our digital transformation initiative.",
        correctAnswer: "catalysts",
        options: ["catalysts", "reasons", "factors", "elements"],
        explanation: "\"Catalysts\" — катализаторы. Метафорическое использование для обозначения ускоряющих факторов.",
      },
      {
        speaker: "A",
        text: "To wrap ___, I'd like to outline our strategic priorities for the upcoming fiscal year.",
        correctAnswer: "up",
        options: ["up", "down", "on", "off"],
        explanation: "\"To wrap up\" — завершить, подвести итог. Стандартный сигнал окончания презентации.",
      },
    ],
  },
];

export function getRandomScenario(difficulty: Difficulty): DialogueScenario {
  const filtered = dialogueScenarios.filter((s) => s.difficulty === difficulty);
  if (filtered.length === 0) {
    return dialogueScenarios[Math.floor(Math.random() * dialogueScenarios.length)];
  }
  return filtered[Math.floor(Math.random() * filtered.length)];
}
