import { GrammarTemplate, GrammarCategory, Difficulty } from "@/types";

const beginnerTenses: GrammarTemplate[] = [
  {
    sentence: "She ___ to the gym every morning before work.",
    options: ["go", "goes", "going", "gone"],
    correct: "goes",
    placeholder: "verb form",
    category: "tenses",
    explanation: "We use the Present Simple with 'she/he/it' + verb ending in -s/-es for regular habits and routines.",
  },
  {
    sentence: "My brother and I ___ basketball on Saturdays.",
    options: ["plays", "play", "playing", "played"],
    correct: "play",
    placeholder: "verb form",
    category: "tenses",
    explanation: "With plural subjects like 'my brother and I', we use the base form of the verb in the Present Simple.",
  },
  {
    sentence: "The train ___ at platform three every hour.",
    options: ["arrive", "arriving", "arrives", "arrived"],
    correct: "arrives",
    placeholder: "verb form",
    category: "tenses",
    explanation: "For scheduled events and timetables, we use the Present Simple with third-person singular subjects.",
  },
  {
    sentence: "They ___ dinner at a lovely restaurant last night.",
    options: ["have", "had", "has", "having"],
    correct: "had",
    placeholder: "verb form",
    category: "tenses",
    explanation: "We use the Past Simple to talk about completed actions at a specific time in the past.",
  },
  {
    sentence: "He ___ his homework right after school yesterday.",
    options: ["finish", "finishes", "finished", "finishing"],
    correct: "finished",
    placeholder: "verb form",
    category: "tenses",
    explanation: "The Past Simple is used for actions completed at a definite time in the past, often with time markers like 'yesterday'.",
  },
  {
    sentence: "We ___ a great movie at the cinema last weekend.",
    options: ["see", "saw", "seen", "seeing"],
    correct: "saw",
    placeholder: "verb form",
    category: "tenses",
    explanation: "'See' is an irregular verb; its past simple form is 'saw'.",
  },
  {
    sentence: "The children ___ in the park every afternoon.",
    options: ["plays", "play", "playing", "played"],
    correct: "play",
    placeholder: "verb form",
    category: "tenses",
    explanation: "With plural subjects, the verb stays in its base form in the Present Simple.",
  },
  {
    sentence: "My mother ___ delicious pasta for dinner every Sunday.",
    options: ["cook", "cooks", "cooking", "cooked"],
    correct: "cooks",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Third-person singular subjects require the '-s' ending in the Present Simple.",
  },
  {
    sentence: "I ___ my keys this morning and couldn't find them for an hour.",
    options: ["lose", "loses", "losing", "lost"],
    correct: "lost",
    placeholder: "verb form",
    category: "tenses",
    explanation: "'Lose' is an irregular verb; its past simple form is 'lost'.",
  },
  {
    sentence: "Does your sister ___ coffee in the morning?",
    options: ["drink", "drinks", "drinking", "drank"],
    correct: "drink",
    placeholder: "verb form",
    category: "tenses",
    explanation: "In questions with 'does', the main verb stays in its base form without '-s'.",
  },
  {
    sentence: "He ___ to music while he works.",
    options: ["listen", "listens", "listening", "listened"],
    correct: "listens",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Present Simple is used for habitual actions; 'he' requires the verb with '-s'.",
  },
  {
    sentence: "We ___ tired after the long walk so we rested.",
    options: ["are", "was", "were", "been"],
    correct: "were",
    placeholder: "verb form",
    category: "tenses",
    explanation: "The past tense of 'be' for 'we' is 'were'.",
  },
  {
    sentence: "She ___ born in a small town near the coast.",
    options: ["is", "was", "were", "been"],
    correct: "was",
    placeholder: "verb form",
    category: "tenses",
    explanation: "We use the Past Simple 'was' (not 'is') to talk about when someone was born.",
  },
  {
    sentence: "The sun ___ in the east and sets in the west.",
    options: ["rise", "rises", "rising", "rose"],
    correct: "rises",
    placeholder: "verb form",
    category: "tenses",
    explanation: "The Present Simple is used for general facts and universal truths.",
  },
  {
    sentence: "My neighbors ___ their dog for a walk twice a day.",
    options: ["take", "takes", "taking", "took"],
    correct: "take",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Plural subjects like 'my neighbors' take the base form of the verb in Present Simple.",
  },
];

const beginnerPrepositions: GrammarTemplate[] = [
  {
    sentence: "The book is ___ the table.",
    options: ["in", "on", "at", "by"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'on' when something is placed on the surface of an object.",
  },
  {
    sentence: "She lives ___ London, not far from the city center.",
    options: ["in", "on", "at", "to"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'in' for large places like cities, countries, or continents.",
  },
  {
    sentence: "The meeting starts ___ 9 o'clock sharp.",
    options: ["in", "on", "at", "by"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'at' for specific times and clock hours.",
  },
  {
    sentence: "I'll see you ___ Monday morning.",
    options: ["in", "on", "at", "by"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'on' for specific days of the week and dates.",
  },
  {
    sentence: "My birthday is ___ July, right in the middle of summer.",
    options: ["in", "on", "at", "by"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'in' for months, seasons, and years.",
  },
  {
    sentence: "She put her phone ___ her bag and zipped it shut.",
    options: ["in", "on", "at", "under"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'in' when something is inside a container or enclosed space.",
  },
  {
    sentence: "There's a beautiful painting hanging ___ the wall.",
    options: ["in", "on", "at", "over"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'on' for things attached to or placed on a vertical surface.",
  },
  {
    sentence: "He's waiting for you ___ the bus stop.",
    options: ["in", "on", "at", "to"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'at' for specific locations, points, and addresses.",
  },
  {
    sentence: "The cat is hiding ___ the sofa.",
    options: ["in", "on", "under", "at"],
    correct: "under",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Under' indicates a position directly below or beneath something.",
  },
  {
    sentence: "I usually go to bed ___ midnight.",
    options: ["in", "on", "at", "by"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'at' for specific points in time, including 'at midnight', 'at noon', and 'at night'.",
  },
  {
    sentence: "We went to the beach ___ the weekend.",
    options: ["in", "on", "at", "by"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "In British English, we use 'at the weekend'; American English also uses 'on the weekend'.",
  },
  {
    sentence: "She arrived ___ the airport just in time for her flight.",
    options: ["in", "on", "at", "to"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'at' for specific locations like airports, stations, and specific buildings.",
  },
  {
    sentence: "There's a cozy cafe ___ the corner of our street.",
    options: ["in", "on", "at", "by"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We say 'on the corner' to refer to the intersection point of two streets.",
  },
  {
    sentence: "He put the milk back ___ the fridge.",
    options: ["in", "on", "at", "onto"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We use 'in' for enclosed spaces like a fridge, room, or box.",
  },
  {
    sentence: "She's been working here ___ 2018.",
    options: ["in", "on", "at", "since"],
    correct: "since",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Since' is used to indicate the starting point of an action that continues to the present.",
  },
];

const beginnerConditionals: GrammarTemplate[] = [
  {
    sentence: "If you ___ water to 100 degrees, it boils.",
    options: ["heat", "heats", "heated", "heating"],
    correct: "heat",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "The zero conditional uses Present Simple in both clauses ('if + present, present') for scientific facts.",
  },
  {
    sentence: "If it ___, the ground gets wet.",
    options: ["rain", "rains", "rained", "raining"],
    correct: "rains",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "In zero conditional, we use Present Simple after 'if' for general truths and logical consequences.",
  },
  {
    sentence: "When you ___ ice in the sun, it melts quickly.",
    options: ["leave", "leaves", "left", "leaving"],
    correct: "leave",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Zero conditionals describe situations that are always true; 'when' can replace 'if' in such cases.",
  },
  {
    sentence: "If you ___ enough sleep, you feel tired the next day.",
    options: ["don't get", "doesn't get", "didn't get", "won't get"],
    correct: "don't get",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Present Simple negative is 'don't + base verb' for subjects other than he/she/it.",
  },
  {
    sentence: "The baby ___ if she is hungry.",
    options: ["cry", "cries", "cried", "crying"],
    correct: "cries",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "The result clause in zero conditional also uses Present Simple, with '-s' for third-person singular.",
  },
  {
    sentence: "If a plant ___ enough water, its leaves turn brown.",
    options: ["doesn't get", "don't get", "didn't get", "won't get"],
    correct: "doesn't get",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "For third-person singular subjects, we use 'doesn't + base verb' in Present Simple negative.",
  },
  {
    sentence: "When the temperature ___ below zero, the lake freezes.",
    options: ["drop", "drops", "dropping", "dropped"],
    correct: "drops",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third-person singular subjects require '-s' on the verb in the Present Simple.",
  },
  {
    sentence: "If you ___ red and blue, you get purple.",
    options: ["mix", "mixes", "mixed", "mixing"],
    correct: "mix",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "In zero conditionals, both clauses use Present Simple to express a constant result.",
  },
  {
    sentence: "I get a headache if I ___ too loudly for too long.",
    options: ["work", "works", "worked", "working"],
    correct: "work",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "The zero conditional can have the 'if' clause at the end; the rule doesn't change.",
  },
  {
    sentence: "If someone ___ me after 10 p.m., I usually don't answer.",
    options: ["call", "calls", "called", "calling"],
    correct: "calls",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "With 'someone' (third-person singular), the verb takes '-s' in Present Simple.",
  },
  {
    sentence: "She ___ nervous when she has to speak in public.",
    options: ["get", "gets", "got", "getting"],
    correct: "gets",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "The result clause uses Present Simple; 'she' needs the verb with '-s'.",
  },
  {
    sentence: "If you ___ a stone into water, it sinks.",
    options: ["throw", "throws", "threw", "throwing"],
    correct: "throw",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "In the 'if' clause of a zero conditional, use the base form for subjects like 'you'.",
  },
  {
    sentence: "Food ___ bad if you leave it out of the fridge for too long.",
    options: ["go", "goes", "went", "going"],
    correct: "goes",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'Food' is an uncountable noun treated as singular, so the verb needs '-s'.",
  },
  {
    sentence: "When I ___ coffee after 5 p.m., I can't sleep at night.",
    options: ["drink", "drinks", "drank", "drinking"],
    correct: "drink",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "The subject 'I' takes the base form of the verb in Present Simple.",
  },
  {
    sentence: "If he ___ in a hurry, he always forgets his keys.",
    options: ["is", "are", "was", "were"],
    correct: "is",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Zero conditionals can use 'be' in Present Simple; 'he' pairs with 'is'.",
  },
];

const beginnerArticles: GrammarTemplate[] = [
  {
    sentence: "I saw ___ dog running across the street.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'a' before singular countable nouns mentioned for the first time, when they begin with a consonant sound.",
  },
  {
    sentence: "She is ___ honest person and everyone trusts her.",
    options: ["a", "an", "the", "no article"],
    correct: "an",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'an' before words that begin with a vowel sound; 'honest' starts with a silent 'h'.",
  },
  {
    sentence: "___ sun is very bright today.",
    options: ["A", "An", "The", "No article"],
    correct: "The",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' when there is only one of something in existence, such as the sun, the moon, the earth.",
  },
  {
    sentence: "He wants to become ___ engineer when he grows up.",
    options: ["a", "an", "the", "no article"],
    correct: "an",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'an' before words starting with a vowel sound; 'engineer' begins with the vowel sound /e/.",
  },
  {
    sentence: "I need to buy ___ milk from the store.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "We don't use an article with uncountable nouns like 'milk' when referring to them in general.",
  },
  {
    sentence: "She has ___ cat and ___ dog at home.",
    options: ["a / a", "a / an", "the / the", "an / a"],
    correct: "a / a",
    placeholder: "article",
    category: "articles",
    explanation: "First mentions of singular countable nouns use 'a' when the words start with consonant sounds.",
  },
  {
    sentence: "___ Amazon is the longest river in South America.",
    options: ["A", "An", "The", "No article"],
    correct: "The",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' before the names of rivers, seas, oceans, and mountain ranges.",
  },
  {
    sentence: "My father is ___ teacher at the local school.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'a' or 'an' when stating someone's profession; 'teacher' begins with a consonant sound.",
  },
  {
    sentence: "___ children are playing in the backyard.",
    options: ["A", "An", "The", "No article"],
    correct: "The",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' when both the speaker and listener know which specific children are being referred to.",
  },
  {
    sentence: "She would like ___ glass of water, please.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "'Glass' starts with a consonant sound, so we use 'a' for this singular countable noun.",
  },
  {
    sentence: "He lives in ___ old house at the end of the street.",
    options: ["a", "an", "the", "no article"],
    correct: "an",
    placeholder: "article",
    category: "articles",
    explanation: "'Old' begins with a vowel sound, so we use 'an' before it.",
  },
  {
    sentence: "___ love is the most important thing in life.",
    options: ["A", "An", "The", "No article"],
    correct: "No article",
    placeholder: "article",
    category: "articles",
    explanation: "Abstract nouns like 'love' used in a general sense do not take an article.",
  },
  {
    sentence: "Can you pass me ___ salt, please?",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' when referring to a specific object that both the speaker and listener know about.",
  },
  {
    sentence: "She bought ___ expensive dress for the party.",
    options: ["a", "an", "the", "no article"],
    correct: "an",
    placeholder: "article",
    category: "articles",
    explanation: "'Expensive' begins with a vowel sound, so 'an' is the correct article.",
  },
  {
    sentence: "___ Mount Everest is the highest peak in the world.",
    options: ["A", "An", "The", "No article"],
    correct: "No article",
    placeholder: "article",
    category: "articles",
    explanation: "We do not use an article before the names of individual mountains.",
  },
];

const beginnerReportedSpeech: GrammarTemplate[] = [
  {
    sentence: "She says that she ___ happy with her new job.",
    options: ["is", "was", "were", "been"],
    correct: "is",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "When the reporting verb 'says' is in the present tense, we don't change the tense in the reported clause.",
  },
  {
    sentence: "He told me that he ___ pizza.",
    options: ["like", "likes", "liked", "liking"],
    correct: "liked",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "When the reporting verb 'told' is in the past, we backshift Present Simple to Past Simple.",
  },
  {
    sentence: "My friend says he ___ coming to the party.",
    options: ["is", "was", "were", "will be"],
    correct: "is",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "With a present-tense reporting verb like 'says', the reported speech keeps its original tense.",
  },
  {
    sentence: "She said that she ___ tired after work.",
    options: ["is", "was", "were", "will be"],
    correct: "was",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Simple 'am/is' changes to Past Simple 'was' in reported speech after a past reporting verb.",
  },
  {
    sentence: "They told us that they ___ the movie already.",
    options: ["see", "saw", "had seen", "will see"],
    correct: "had seen",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple changes to Past Perfect in reported speech. 'Saw' becomes 'had seen'.",
  },
  {
    sentence: "He says he ___ never been abroad before.",
    options: ["has", "had", "have", "will have"],
    correct: "has",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "When the reporting verb is in the present ('says'), the present perfect stays the same.",
  },
  {
    sentence: "She said she ___ call me later that evening.",
    options: ["will", "would", "can", "could"],
    correct: "would",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Will' changes to 'would' in reported speech when the reporting verb is in the past.",
  },
  {
    sentence: "My brother told me he ___ his wallet on the bus.",
    options: ["lose", "lost", "had lost", "loses"],
    correct: "had lost",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'lost' becomes Past Perfect 'had lost' in reported speech.",
  },
  {
    sentence: "They say they ___ going to visit us next month.",
    options: ["are", "were", "will be", "have been"],
    correct: "are",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "With a present reporting verb 'say', we keep the original tense in the reported clause.",
  },
  {
    sentence: "He told me he ___ at the office all day.",
    options: ["is", "was", "will be", "have been"],
    correct: "was",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Am/is' becomes 'was' after a past reporting verb like 'told'.",
  },
  {
    sentence: "She said that she ___ marry him.",
    options: ["doesn't want to", "didn't want to", "won't want to", "wouldn't want to"],
    correct: "didn't want to",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Simple 'doesn't want' backshifts to Past Simple 'didn't want' in reported speech.",
  },
  {
    sentence: "The teacher told us that water ___ at 100 degrees Celsius.",
    options: ["boils", "boiled", "had boiled", "is boiling"],
    correct: "boils",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Universal truths and facts don't change tense in reported speech, even with a past reporting verb.",
  },
  {
    sentence: "My mother says she ___ a delicious cake for my birthday.",
    options: ["made", "makes", "had made", "will make"],
    correct: "will make",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "With a present reporting verb, we keep the original future tense.",
  },
  {
    sentence: "He said that they ___ to move to a new apartment.",
    options: ["plan", "plans", "planned", "had planned"],
    correct: "planned",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Simple 'plan' backshifts to Past Simple 'planned' after a past reporting verb.",
  },
  {
    sentence: "She told me she ___ speak three languages.",
    options: ["can", "could", "will", "would"],
    correct: "could",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Can' changes to 'could' in reported speech when the reporting verb is in the past.",
  },
];

const beginnerModals: GrammarTemplate[] = [
  {
    sentence: "I ___ swim very well; I've been taking lessons for years.",
    options: ["can", "will", "must", "should"],
    correct: "can",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Can' is used to express ability in the present.",
  },
  {
    sentence: "___ you help me carry these boxes upstairs?",
    options: ["Can", "Must", "Should", "Will"],
    correct: "Can",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Can' is used to make polite requests and ask for help.",
  },
  {
    sentence: "When I was younger, I ___ run ten kilometers without stopping.",
    options: ["can", "could", "will", "would"],
    correct: "could",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Could' is the past form of 'can', used to talk about past ability.",
  },
  {
    sentence: "She ___ probably arrive around 7 p.m. depending on traffic.",
    options: ["can", "will", "must", "should"],
    correct: "will",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Will' is used to express future predictions and certainty.",
  },
  {
    sentence: "I promise I ___ be late again.",
    options: ["can't", "won't", "mustn't", "shouldn't"],
    correct: "won't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Won't' (will not) expresses a promise or determination about the future.",
  },
  {
    sentence: "___ I open the window? It's getting a bit warm in here.",
    options: ["Will", "Must", "Can", "Should"],
    correct: "Can",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Can' is used to ask for permission in informal situations.",
  },
  {
    sentence: "We ___ be at the airport by 6 a.m. to catch our flight.",
    options: ["can", "will", "could", "should"],
    correct: "will",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Will' expresses a future action that is planned or certain.",
  },
  {
    sentence: "He ___ play the guitar when he was only five years old.",
    options: ["can", "could", "will", "must"],
    correct: "could",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Could' is used for past ability, especially when the ability was acquired at a young age.",
  },
  {
    sentence: "I'm sorry, but I ___ come to your party on Saturday.",
    options: ["can't", "won't", "mustn't", "shouldn't"],
    correct: "can't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Can't' (cannot) expresses inability or impossibility in the present.",
  },
  {
    sentence: "___ you please turn down the music? I'm trying to study.",
    options: ["Must", "Should", "Will", "Could"],
    correct: "Could",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Could' is a polite way to make requests, more formal than 'can'.",
  },
  {
    sentence: "She ___ be very excited about her new job offer.",
    options: ["can", "must", "will", "could"],
    correct: "will",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Will' expresses a natural or expected reaction.",
  },
  {
    sentence: "I ___ speak French when I was a child, but I've forgotten most of it now.",
    options: ["can", "could", "will", "would"],
    correct: "could",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Could' refers to a past ability that no longer exists.",
  },
  {
    sentence: "Don't worry, everything ___ be fine in the end.",
    options: ["can", "could", "will", "must"],
    correct: "will",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Will' is used to offer reassurance about the future.",
  },
  {
    sentence: "Birds ___ fly, but penguins cannot.",
    options: ["can", "will", "must", "should"],
    correct: "can",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Can' expresses general ability — what is generally possible.",
  },
  {
    sentence: "I ___ definitely help you with your homework after dinner.",
    options: ["can", "will", "shall", "must"],
    correct: "will",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Will' expresses a definite intention or promise.",
  },
];

const intermediateTenses: GrammarTemplate[] = [
  {
    sentence: "She ___ in London for three years now and loves it there.",
    options: ["lives", "lived", "has lived", "is living"],
    correct: "has lived",
    placeholder: "verb form",
    category: "tenses",
    explanation: "We use the Present Perfect for actions that started in the past and continue to the present, often with 'for' and 'since'.",
  },
  {
    sentence: "I ___ my keys again. Can you help me look for them?",
    options: ["lose", "lost", "have lost", "was losing"],
    correct: "have lost",
    placeholder: "verb form",
    category: "tenses",
    explanation: "The Present Perfect is used for past actions with present relevance or results.",
  },
  {
    sentence: "While I ___ dinner, the phone rang.",
    options: ["cook", "cooked", "have cooked", "was cooking"],
    correct: "was cooking",
    placeholder: "verb form",
    category: "tenses",
    explanation: "We use the Past Continuous for an ongoing action interrupted by another action in the past.",
  },
  {
    sentence: "They ___ each other since they were children.",
    options: ["know", "knew", "have known", "are knowing"],
    correct: "have known",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Present Perfect is used with 'since' to show the starting point of a state that continues.",
  },
  {
    sentence: "He ___ at his computer when the power went out.",
    options: ["works", "worked", "has worked", "was working"],
    correct: "was working",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Continuous describes an action in progress at a specific moment in the past.",
  },
  {
    sentence: "We ___ that restaurant yet, but we've heard great things about it.",
    options: ["don't try", "didn't try", "haven't tried", "weren't trying"],
    correct: "haven't tried",
    placeholder: "verb form",
    category: "tenses",
    explanation: "We use the Present Perfect negative with 'yet' for things expected to happen but still incomplete.",
  },
  {
    sentence: "She ___ on the report all morning and still hasn't finished.",
    options: ["works", "worked", "has been working", "was working"],
    correct: "has been working",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Present Perfect Continuous emphasizes the ongoing duration of an action that started in the past.",
  },
  {
    sentence: "When I arrived at the station, the train already ___.",
    options: ["leaves", "left", "has left", "had left"],
    correct: "had left",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect shows an action completed before another past action.",
  },
  {
    sentence: "It ___ all day yesterday, so we stayed indoors.",
    options: ["rains", "rained", "has rained", "was raining"],
    correct: "was raining",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Continuous can describe an ongoing situation over a period of time in the past.",
  },
  {
    sentence: "By this time next year, we ___ our house.",
    options: ["renovated", "will have renovated", "have renovated", "are renovating"],
    correct: "will have renovated",
    placeholder: "verb form",
    category: "tenses",
    explanation: "The Future Perfect expresses an action that will be completed before a specific time in the future.",
  },
  {
    sentence: "He ___ at this company since he graduated from university.",
    options: ["works", "worked", "has worked", "was working"],
    correct: "has worked",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Present Perfect with 'since' links a past starting point to the present.",
  },
  {
    sentence: "While they ___ through the park, they found an abandoned puppy.",
    options: ["walk", "walked", "have walked", "were walking"],
    correct: "were walking",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Continuous sets the scene for an unexpected event in the past.",
  },
  {
    sentence: "I ___ to Japan three times so far, and I'd love to go again.",
    options: ["go", "went", "have been", "was going"],
    correct: "have been",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Present Perfect with 'so far' or specific number of times expresses life experiences.",
  },
  {
    sentence: "She realized she ___ her passport at home only when she got to the airport.",
    options: ["leaves", "left", "has left", "had left"],
    correct: "had left",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect indicates an action completed before another past event (realizing at the airport).",
  },
  {
    sentence: "I ___ for you outside the cinema when I saw the accident.",
    options: ["wait", "waited", "have waited", "was waiting"],
    correct: "was waiting",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Continuous describes what someone was doing when something else happened.",
  },
];

const intermediatePrepositions: GrammarTemplate[] = [
  {
    sentence: "She's been interested ___ art ever since she visited the Louvre.",
    options: ["in", "on", "at", "about"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "The adjective 'interested' is always followed by the preposition 'in'.",
  },
  {
    sentence: "I apologize ___ arriving late; the traffic was terrible.",
    options: ["for", "about", "to", "of"],
    correct: "for",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We say 'apologize for' something. 'Apologize for + verb-ing' is the correct pattern.",
  },
  {
    sentence: "He's really good ___ solving complex puzzles.",
    options: ["in", "on", "at", "with"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Good at' is the standard collocation for skills and abilities.",
  },
  {
    sentence: "She insisted ___ paying for the entire meal.",
    options: ["to", "in", "on", "for"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "The verb 'insist' is followed by 'on + verb-ing' or 'on + noun'.",
  },
  {
    sentence: "We're looking forward ___ seeing you next weekend.",
    options: ["to", "for", "at", "in"],
    correct: "to",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Look forward to' is always followed by a noun or gerund, not an infinitive.",
  },
  {
    sentence: "She was accused ___ stealing money from the company.",
    options: ["for", "of", "with", "by"],
    correct: "of",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Accused of' is the correct prepositional phrase for blaming someone.",
  },
  {
    sentence: "The hotel room consisted ___ a bed, a desk, and a small bathroom.",
    options: ["of", "in", "from", "with"],
    correct: "of",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Consist of' means 'to be made up of' and is always followed by 'of'.",
  },
  {
    sentence: "He succeeded ___ passing the exam on his first attempt.",
    options: ["to", "in", "on", "at"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Succeed in + verb-ing' is the correct pattern.",
  },
  {
    sentence: "I'm not familiar ___ the rules of this game at all.",
    options: ["to", "with", "about", "for"],
    correct: "with",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Familiar with' means having knowledge or experience of something.",
  },
  {
    sentence: "She applied ___ a job at the new hospital downtown.",
    options: ["to", "for", "in", "at"],
    correct: "for",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Apply for' a job/position; 'apply to' a university or institution.",
  },
  {
    sentence: "They blamed the accident ___ the bad weather conditions.",
    options: ["to", "on", "for", "with"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "We 'blame something on something' or 'blame someone for something'.",
  },
  {
    sentence: "I completely agree ___ you about the new policy.",
    options: ["to", "with", "on", "about"],
    correct: "with",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Agree with' a person; 'agree to' a proposal; 'agree on' a matter.",
  },
  {
    sentence: "She's been suffering ___ severe headaches for weeks.",
    options: ["of", "from", "with", "for"],
    correct: "from",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Suffer from' an illness or condition is the standard collocation.",
  },
  {
    sentence: "The children were excited ___ going to the amusement park.",
    options: ["about", "for", "to", "with"],
    correct: "about",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Excited about' is the correct prepositional pattern for anticipation.",
  },
  {
    sentence: "He dedicated his entire life ___ helping underprivileged communities.",
    options: ["to", "for", "in", "on"],
    correct: "to",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Dedicate something to + noun/gerund' is the correct pattern.",
  },
];

const intermediateConditionals: GrammarTemplate[] = [
  {
    sentence: "If it ___ tomorrow, we'll cancel the picnic.",
    options: ["rain", "rains", "rained", "will rain"],
    correct: "rains",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "In the first conditional, we use Present Simple in the 'if' clause and 'will' in the result clause.",
  },
  {
    sentence: "If I ___ rich, I would travel around the world.",
    options: ["am", "was", "were", "will be"],
    correct: "were",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "The second conditional uses 'were' for all subjects (subjunctive) in the 'if' clause with hypothetical situations.",
  },
  {
    sentence: "She'll miss the bus if she ___ soon.",
    options: ["doesn't leave", "didn't leave", "won't leave", "wouldn't leave"],
    correct: "doesn't leave",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "First conditional: Present Simple in the 'if' clause (even when negative).",
  },
  {
    sentence: "If he ___ harder, he could pass the exam easily.",
    options: ["study", "studies", "studied", "will study"],
    correct: "studied",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Second conditional: Past Simple in 'if' clause for unreal/hypothetical present situations.",
  },
  {
    sentence: "We'll go to the beach as long as the weather ___ nice.",
    options: ["is", "will be", "would be", "was"],
    correct: "is",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'As long as' functions like 'if' in the first conditional — Present Simple in the condition clause.",
  },
  {
    sentence: "If I ___ you, I'd accept the job offer immediately.",
    options: ["am", "was", "were", "will be"],
    correct: "were",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'If I were you' is a fixed subjunctive expression used to give advice about hypothetical situations.",
  },
  {
    sentence: "You ___ the exam unless you start studying more seriously.",
    options: ["fail", "will fail", "would fail", "failed"],
    correct: "will fail",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'Unless' means 'if not'; the result clause in first conditional uses 'will + base verb'.",
  },
  {
    sentence: "What would you do if you ___ a million dollars in the lottery?",
    options: ["win", "wins", "won", "will win"],
    correct: "won",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Second conditional: Past Simple in the 'if' clause for imaginary situations in the present/future.",
  },
  {
    sentence: "If you ___ the instructions carefully, you won't have any problems.",
    options: ["follow", "follows", "followed", "will follow"],
    correct: "follow",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "First conditional: base form after 'you' in the Present Simple 'if' clause.",
  },
  {
    sentence: "She ___ happier if she spent less time on social media.",
    options: ["is", "was", "would be", "will be"],
    correct: "would be",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Second conditional result clause uses 'would + base verb' for hypothetical results.",
  },
  {
    sentence: "We ___ the project on time provided that everyone does their part.",
    options: ["finish", "finished", "will finish", "would finish"],
    correct: "will finish",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'Provided that' works like 'if' in first conditional; use 'will + base verb' in the result clause.",
  },
  {
    sentence: "If I ___ in a bigger city, I would go to more cultural events.",
    options: ["live", "lives", "lived", "will live"],
    correct: "lived",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Second conditional uses Past Simple in the 'if' clause for unreal present situations.",
  },
  {
    sentence: "If you're feeling unwell, you ___ go home and rest.",
    options: ["will", "should", "would", "could"],
    correct: "should",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "In conditional sentences, we can use modal verbs like 'should' in the result clause for advice.",
  },
  {
    sentence: "If I ___ enough money saved, I'd buy a new car right now.",
    options: ["have", "had", "will have", "would have"],
    correct: "had",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Second conditional: Past Simple 'had' expresses an unreal present situation.",
  },
  {
    sentence: "You can borrow my car as long as you ___ it back by 6 p.m.",
    options: ["bring", "brings", "brought", "will bring"],
    correct: "bring",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'As long as' + Present Simple is used for real future conditions.",
  },
];

const intermediateArticles: GrammarTemplate[] = [
  {
    sentence: "We spent a week in ___ Netherlands last summer.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' with country names that are plural or include words like 'kingdom', 'states', 'republic'.",
  },
  {
    sentence: "She has ___ great sense of humor; everyone loves her jokes.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "'Sense' is a countable noun introduced for the first time and starts with a consonant sound.",
  },
  {
    sentence: "He's studying ___ history of ancient Rome at university.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' with 'history of' when referring to a specific historical subject.",
  },
  {
    sentence: "I love listening to ___ music when I'm working.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "Uncountable nouns like 'music' used in a general sense take no article.",
  },
  {
    sentence: "___ information you provided was very helpful for our research.",
    options: ["A", "An", "The", "No article"],
    correct: "The",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' with uncountable nouns when referring to a specific instance.",
  },
  {
    sentence: "She speaks ___ French fluently after living in Paris for five years.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "We do not use articles before the names of languages when used after 'speak'.",
  },
  {
    sentence: "He's ___ only person I trust with this confidential information.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' before superlatives and words like 'only', 'first', 'last'.",
  },
  {
    sentence: "My sister works at ___ hospital on the other side of town.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' when the noun is defined by additional information (specified as 'on the other side of town').",
  },
  {
    sentence: "___ happiness is more important than money.",
    options: ["A", "An", "The", "No article"],
    correct: "No article",
    placeholder: "article",
    category: "articles",
    explanation: "Abstract nouns used in a general sense take no article.",
  },
  {
    sentence: "I had ___ very interesting conversation with your brother yesterday.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "'Conversation' is a singular countable noun mentioned for the first time; 'very' starts with a consonant sound.",
  },
  {
    sentence: "We're going to watch ___ new film that everyone is talking about.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "'The' is used because the film is specifically identified by the relative clause 'that everyone is talking about'.",
  },
  {
    sentence: "She goes to ___ bed at ten o'clock every night.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "We don't use an article in the expression 'go to bed' when referring to the activity of sleeping.",
  },
  {
    sentence: "He arrived at ___ school early to prepare for the presentation.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "No article is used with 'school', 'college', 'hospital', 'church' when referring to their primary purpose.",
  },
  {
    sentence: "They took ___ taxi to the airport because they were running late.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'a' with means of transport when mentioned in a general, non-specific way.",
  },
  {
    sentence: "___ most people enjoy spending time with their families during holidays.",
    options: ["A", "An", "The", "No article"],
    correct: "No article",
    placeholder: "article",
    category: "articles",
    explanation: "'Most' + plural noun in a general sense does not require an article.",
  },
];

const intermediateReportedSpeech: GrammarTemplate[] = [
  {
    sentence: "She told me that she ___ the report before the meeting.",
    options: ["finishes", "finished", "had finished", "has finished"],
    correct: "had finished",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'finished' shifts to Past Perfect 'had finished' in reported speech.",
  },
  {
    sentence: "He asked me if I ___ help him with the presentation.",
    options: ["can", "could", "will", "would"],
    correct: "could",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Can' changes to 'could' in reported questions with a past reporting verb.",
  },
  {
    sentence: "The manager announced that the company ___ a new branch next year.",
    options: ["opens", "opened", "would open", "had opened"],
    correct: "would open",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Will' changes to 'would' in reported speech when the reporting verb is in the past.",
  },
  {
    sentence: "She wondered where he ___ from.",
    options: ["comes", "came", "had come", "will come"],
    correct: "came",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "In reported questions, Present Simple 'comes' backshifts to Past Simple 'came' after a past reporting verb.",
  },
  {
    sentence: "He admitted that he ___ a mistake.",
    options: ["made", "makes", "had made", "will make"],
    correct: "had made",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'made' becomes Past Perfect 'had made' in reported speech with a past reporting verb.",
  },
  {
    sentence: "She told me she ___ working on the project since January.",
    options: ["is", "was", "had been", "has been"],
    correct: "had been",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Perfect Continuous 'has been working' shifts to Past Perfect Continuous 'had been working'.",
  },
  {
    sentence: "He asked if we ___ the documentary the previous night.",
    options: ["watch", "watched", "had watched", "will watch"],
    correct: "had watched",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'watched' shifts further back to Past Perfect 'had watched' in reported speech.",
  },
  {
    sentence: "She said that they ___ going to move to Berlin.",
    options: ["are", "were", "had been", "will be"],
    correct: "were",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Are going to' shifts to 'were going to' in reported speech with a past reporting verb.",
  },
  {
    sentence: "My colleague told me he ___ submit the application the following day.",
    options: ["will", "would", "can", "could"],
    correct: "would",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Will' changes to 'would' and 'tomorrow' changes to 'the following day' in reported speech.",
  },
  {
    sentence: "She promised that she ___ me every day while traveling.",
    options: ["calls", "called", "would call", "had called"],
    correct: "would call",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Will call' becomes 'would call' when reported after a past reporting verb.",
  },
  {
    sentence: "He claimed that he ___ the email before the deadline.",
    options: ["sends", "sent", "had sent", "would send"],
    correct: "had sent",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'sent' shifts to Past Perfect 'had sent' to show the action happened before the claim.",
  },
  {
    sentence: "She wanted to know if I ___ to the concert the following Saturday.",
    options: ["go", "went", "was going", "had gone"],
    correct: "was going",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Continuous 'am going' backshifts to Past Continuous 'was going' in reported speech.",
  },
  {
    sentence: "He explained that the train ___ late due to an accident on the tracks.",
    options: ["is", "was", "had been", "will be"],
    correct: "was",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Simple 'is' backshifts to Past Simple 'was' after 'explained' (past tense).",
  },
  {
    sentence: "She confessed that she ___ the last slice of cake.",
    options: ["eats", "ate", "had eaten", "was eating"],
    correct: "had eaten",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'ate' shifts to Past Perfect 'had eaten' in reported speech.",
  },
  {
    sentence: "They asked if we ever ___ to New Zealand before.",
    options: ["go", "went", "had been", "have been"],
    correct: "had been",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Perfect 'have been' shifts to Past Perfect 'had been' in reported speech.",
  },
];

const intermediateModals: GrammarTemplate[] = [
  {
    sentence: "You ___ wear a helmet when riding a motorcycle; it's the law.",
    options: ["can", "might", "must", "could"],
    correct: "must",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Must' expresses strong obligation, especially when required by law or rules.",
  },
  {
    sentence: "She ___ be at home by now; she left the office an hour ago.",
    options: ["can", "must", "might", "should"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should' expresses a logical expectation or probability based on known facts.",
  },
  {
    sentence: "I'm not sure, but he ___ change his mind about the trip.",
    options: ["must", "should", "might", "can"],
    correct: "might",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Might' expresses possibility — something that could happen but is uncertain.",
  },
  {
    sentence: "We ___ have left earlier; now we're stuck in traffic.",
    options: ["must", "should", "might", "could"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have + past participle' expresses regret about a past action that would have been better.",
  },
  {
    sentence: "You ___ smoke inside the building; it's strictly prohibited.",
    options: ["shouldn't", "mightn't", "mustn't", "couldn't"],
    correct: "mustn't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Mustn't' (must not) expresses prohibition — something that is not allowed.",
  },
  {
    sentence: "He looks very pale; he ___ be feeling unwell.",
    options: ["can", "must", "might", "should"],
    correct: "might",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Might' is used to speculate about possible reasons for something observed.",
  },
  {
    sentence: "You really ___ see a doctor about that persistent cough.",
    options: ["can", "must", "might", "should"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should' is used to give advice or recommendations.",
  },
  {
    sentence: "I ___ have forgotten my keys at the office; I can't find them anywhere.",
    options: ["must", "should", "might", "would"],
    correct: "must",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Must have + past participle' expresses a strong logical deduction about the past.",
  },
  {
    sentence: "Children under twelve ___ be accompanied by an adult in this area.",
    options: ["can", "must", "might", "should"],
    correct: "must",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Must' is used for formal rules and requirements.",
  },
  {
    sentence: "She ___ have taken the documents; she was the last person in the office.",
    options: ["can", "must", "might", "should"],
    correct: "might",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Might have + past participle' expresses a possibility about a past action.",
  },
  {
    sentence: "You ___ try the seafood pasta; it's the chef's specialty.",
    options: ["must", "should", "might", "can"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should' is used to give a strong recommendation or suggestion.",
  },
  {
    sentence: "He ___ be the new manager; he's been sitting in that office all morning.",
    options: ["can", "must", "might", "should"],
    correct: "must",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Must' expresses a confident deduction based on observable evidence.",
  },
  {
    sentence: "We ___ have booked the tickets earlier; they're sold out now.",
    options: ["must", "should", "might", "could"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have + past participle' expresses regret about not doing something in the past.",
  },
  {
    sentence: "The meeting ___ last longer than expected, so don't schedule anything else.",
    options: ["must", "should", "might", "can"],
    correct: "might",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Might' expresses a real possibility — the meeting could go long.",
  },
  {
    sentence: "Passengers ___ fasten their seatbelts during takeoff and landing.",
    options: ["can", "must", "might", "should"],
    correct: "must",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Must' is used for mandatory safety instructions and rules.",
  },
];

const advancedTenses: GrammarTemplate[] = [
  {
    sentence: "By the time the ambulance arrived, the man ___ consciousness.",
    options: ["regains", "regained", "had regained", "has regained"],
    correct: "had regained",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect is used for an action completed before another past action ('by the time the ambulance arrived').",
  },
  {
    sentence: "She ___ for this company for twenty years by next March.",
    options: ["works", "will work", "will have worked", "has worked"],
    correct: "will have worked",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect is used with 'by + future time' to express an action that will be completed before that time.",
  },
  {
    sentence: "He ___ the report before the client called to request changes.",
    options: ["submits", "submitted", "had submitted", "has submitted"],
    correct: "had submitted",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect shows that submitting the report happened before the client called.",
  },
  {
    sentence: "By the end of this year, we ___ in this house for a decade.",
    options: ["live", "will live", "will have lived", "have lived"],
    correct: "will have lived",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect expresses duration up to a specific point in the future.",
  },
  {
    sentence: "I realized I ___ the same mistake again when I reviewed the calculations.",
    options: ["make", "made", "had made", "was making"],
    correct: "had made",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect for an action completed before the moment of realization.",
  },
  {
    sentence: "The researchers ___ the experiment three times by the time they publish their findings.",
    options: ["conduct", "will conduct", "will have conducted", "have conducted"],
    correct: "will have conducted",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect shows completion of repeated actions before a future reference point.",
  },
  {
    sentence: "She ___ to call me before she showed up at my doorstep.",
    options: ["forgets", "forgot", "had forgotten", "has forgotten"],
    correct: "had forgotten",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect indicates that forgetting happened before she arrived.",
  },
  {
    sentence: "By the time you read this message, I ___ already left for the airport.",
    options: ["have", "will have", "had", "am having"],
    correct: "will have",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect is used to describe an action that will be completed before another future event.",
  },
  {
    sentence: "The detective realized that someone ___ with the evidence before he arrived.",
    options: ["tampers", "tampered", "had tampered", "has tampered"],
    correct: "had tampered",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect shows the tampering occurred before the detective's realization.",
  },
  {
    sentence: "By the summer of 2027, they ___ their new headquarters.",
    options: ["complete", "will complete", "will have completed", "have completed"],
    correct: "will have completed",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect is used with a specific future date to show completion by then.",
  },
  {
    sentence: "He was exhausted because he ___ for twelve hours straight.",
    options: ["works", "worked", "had been working", "has been working"],
    correct: "had been working",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect Continuous emphasizes the duration of an action leading up to a past result.",
  },
  {
    sentence: "By next week, I ___ every episode of this series.",
    options: ["watch", "will watch", "will have watched", "have watched"],
    correct: "will have watched",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect for an action that will be completed by a specific future time.",
  },
  {
    sentence: "The garden was flooded because it ___ heavily all night.",
    options: ["rains", "rained", "had been raining", "has been raining"],
    correct: "had been raining",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect Continuous indicates the ongoing rain that led to the flooding.",
  },
  {
    sentence: "By the time they retire, they ___ enough money to travel the world.",
    options: ["save", "will save", "will have saved", "have saved"],
    correct: "will have saved",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Future Perfect to show accumulation completed before retirement.",
  },
  {
    sentence: "She ___ her degree before she started her first job.",
    options: ["finishes", "finished", "had finished", "has finished"],
    correct: "had finished",
    placeholder: "verb form",
    category: "tenses",
    explanation: "Past Perfect clarifies the chronological order: degree first, then job.",
  },
];

const advancedPrepositions: GrammarTemplate[] = [
  {
    sentence: "His success can be attributed ___ years of hard work and dedication.",
    options: ["to", "for", "with", "on"],
    correct: "to",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Attributed to' is the correct collocation meaning 'caused by' or 'credited to'.",
  },
  {
    sentence: "She has a remarkable talent ___ making people feel at ease.",
    options: ["of", "for", "in", "about"],
    correct: "for",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Talent for + gerund/noun' is the standard prepositional pattern.",
  },
  {
    sentence: "The new regulations are aimed ___ reducing carbon emissions by 40 percent.",
    options: ["to", "at", "for", "on"],
    correct: "at",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Aimed at + gerund' means 'intended to achieve' a particular goal.",
  },
  {
    sentence: "He was oblivious ___ the fact that everyone was waiting for him.",
    options: ["to", "of", "about", "for"],
    correct: "to",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Oblivious to' means unaware of something; 'to' is the correct preposition.",
  },
  {
    sentence: "She takes great pride ___ her children's academic achievements.",
    options: ["to", "in", "on", "about"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Take pride in' is a fixed collocation meaning to feel satisfaction about something.",
  },
  {
    sentence: "The CEO is notorious ___ making controversial public statements.",
    options: ["to", "for", "about", "with"],
    correct: "for",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Notorious for + gerund/noun' is the correct pattern for being well-known for something negative.",
  },
  {
    sentence: "I'm deeply indebted ___ you for all the support you've given me.",
    options: ["for", "to", "with", "by"],
    correct: "to",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Indebted to' a person, 'indebted for' the thing received. Both can appear in one sentence.",
  },
  {
    sentence: "The outcome is contingent ___ the board's final decision.",
    options: ["to", "on", "with", "for"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Contingent on/upon' means dependent on something else happening.",
  },
  {
    sentence: "She has no recollection ___ the events that took place that evening.",
    options: ["to", "of", "for", "about"],
    correct: "of",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Recollection of' is the correct pattern meaning memory of something.",
  },
  {
    sentence: "The company is renowned ___ its innovative approach to sustainable design.",
    options: ["to", "for", "with", "about"],
    correct: "for",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Renowned for' means famous or well-known for a particular quality.",
  },
  {
    sentence: "We need to liaise ___ the marketing department before launching the campaign.",
    options: ["to", "with", "for", "about"],
    correct: "with",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Liaise with' means to establish a working relationship or communication channel.",
  },
  {
    sentence: "He is adamant ___ not accepting any compromise on the quality standards.",
    options: ["in", "on", "about", "for"],
    correct: "about",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Adamant about' means firmly determined and unwilling to change one's mind.",
  },
  {
    sentence: "Her approach to teaching is predicated ___ the belief that every child can learn.",
    options: ["to", "on", "with", "for"],
    correct: "on",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Predicated on' means based on or founded upon a particular assumption.",
  },
  {
    sentence: "The investigation is hampered ___ a lack of credible witnesses.",
    options: ["by", "with", "from", "to"],
    correct: "by",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Hampered by' means hindered or made more difficult by something.",
  },
  {
    sentence: "She was engrossed ___ the novel and didn't hear me come in.",
    options: ["with", "in", "by", "to"],
    correct: "in",
    placeholder: "preposition",
    category: "prepositions",
    explanation: "'Engrossed in' means completely absorbed or focused on something.",
  },
];

const advancedConditionals: GrammarTemplate[] = [
  {
    sentence: "If I ___ about the traffic, I would have left earlier.",
    options: ["know", "knew", "had known", "would know"],
    correct: "had known",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional: 'if + Past Perfect, would have + past participle' for unreal past situations.",
  },
  {
    sentence: "She ___ the flight if she hadn't set three alarms.",
    options: ["misses", "missed", "would have missed", "had missed"],
    correct: "would have missed",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional result clause uses 'would have + past participle'.",
  },
  {
    sentence: "If I had learned Spanish as a child, I ___ bilingual now.",
    options: ["am", "was", "would be", "had been"],
    correct: "would be",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Mixed conditional: Past Perfect in 'if' clause (past) + 'would + base' for present result.",
  },
  {
    sentence: "He wouldn't be so successful now if he ___ his education.",
    options: ["neglects", "neglected", "had neglected", "would neglect"],
    correct: "had neglected",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Mixed conditional: 'would + base' (present result) + Past Perfect (unreal past condition).",
  },
  {
    sentence: "If the rescue team ___ sooner, the hikers might have survived.",
    options: ["arrives", "arrived", "had arrived", "would arrive"],
    correct: "had arrived",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional with 'might have' instead of 'would have' for a less certain result.",
  },
  {
    sentence: "I ___ the job if I had prepared better for the interview.",
    options: ["get", "got", "would have gotten", "had gotten"],
    correct: "would have gotten",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional: unreal past condition with a hypothetical past result.",
  },
  {
    sentence: "If she weren't so talented, she ___ the lead role in the play.",
    options: ["doesn't get", "didn't get", "wouldn't have gotten", "hadn't gotten"],
    correct: "wouldn't have gotten",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Mixed conditional: present condition ('weren't') with a past result.",
  },
  {
    sentence: "We ___ the deadline if we hadn't worked overtime all week.",
    options: ["miss", "missed", "would have missed", "had missed"],
    correct: "would have missed",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional expresses how a different past action would have changed the outcome.",
  },
  {
    sentence: "If the weather ___ better last weekend, we could have gone hiking.",
    options: ["is", "was", "had been", "would be"],
    correct: "had been",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional: Past Perfect after 'if' for an unreal past condition.",
  },
  {
    sentence: "She ___ here now if her flight hadn't been delayed.",
    options: ["is", "was", "would be", "had been"],
    correct: "would be",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Mixed conditional: Past Perfect in the condition (past) with 'would + base' for a present result.",
  },
  {
    sentence: "If you ___ the contract more carefully, you wouldn't have signed it.",
    options: ["read", "had read", "would read", "were reading"],
    correct: "had read",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional for an unreal past situation and its hypothetical consequence.",
  },
  {
    sentence: "They ___ the house if they had known about the structural problems.",
    options: ["don't buy", "didn't buy", "wouldn't have bought", "hadn't bought"],
    correct: "wouldn't have bought",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional negative result clause: 'wouldn't have + past participle'.",
  },
  {
    sentence: "If I ___ the courage to speak up back then, things might be different today.",
    options: ["have", "had", "had had", "would have"],
    correct: "had had",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Mixed conditional: 'had had' (Past Perfect of 'have') for an unreal past condition affecting the present.",
  },
  {
    sentence: "He ___ the promotion if he hadn't consistently exceeded his targets.",
    options: ["doesn't get", "didn't get", "wouldn't have gotten", "won't get"],
    correct: "wouldn't have gotten",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "Third conditional negative expressing a hypothetical different outcome.",
  },
  {
    sentence: "If only I ___ to her advice, I wouldn't be in this situation now.",
    options: ["listen", "listened", "had listened", "would listen"],
    correct: "had listened",
    placeholder: "verb form",
    category: "conditionals",
    explanation: "'If only' + Past Perfect expresses regret about a past action affecting the present.",
  },
];

const advancedArticles: GrammarTemplate[] = [
  {
    sentence: "She has been appointed ___ chairperson of the newly formed committee.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "No article is used before unique professional titles that refer to a specific single position.",
  },
  {
    sentence: "He went to ___ prison to visit his uncle who was serving a sentence there.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "'The prison' refers to a specific building. Compare with 'go to prison' (as an inmate, no article).",
  },
  {
    sentence: "___ French are known for their exquisite cuisine and fine wines.",
    options: ["A", "An", "The", "No article"],
    correct: "The",
    placeholder: "article",
    category: "articles",
    explanation: "'The' + nationality adjective refers to the people of that nation as a whole.",
  },
  {
    sentence: "It's ___ pity that you couldn't attend the ceremony.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "'It's a pity' is a fixed expression; 'pity' starts with a consonant sound.",
  },
  {
    sentence: "She has ___ deep understanding of quantum mechanics.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "'Understanding' can be used as a countable noun with 'a/an' when qualified by an adjective.",
  },
  {
    sentence: "We traveled across ___ Sahara Desert during our expedition.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "We use 'the' with deserts, mountain ranges, rivers, and other geographical features.",
  },
  {
    sentence: "He's studying to become ___ architect specializing in sustainable design.",
    options: ["a", "an", "the", "no article"],
    correct: "an",
    placeholder: "article",
    category: "articles",
    explanation: "'Architect' begins with a vowel sound, so 'an' is used for this profession.",
  },
  {
    sentence: "In ___ case of emergency, break the glass and press the button.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "'In case of' is a fixed prepositional phrase that takes no article.",
  },
  {
    sentence: "___ number of students applying to this program has doubled.",
    options: ["A", "An", "The", "No article"],
    correct: "The",
    placeholder: "article",
    category: "articles",
    explanation: "'The number of' refers to a specific figure — the actual count. Compare with 'a number of' (several).",
  },
  {
    sentence: "He gave me ___ invaluable advice on starting my own business.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "'Advice' is uncountable and takes no article when modified by an adjective.",
  },
  {
    sentence: "She speaks with ___ authority that commands respect from everyone in the room.",
    options: ["a", "an", "the", "no article"],
    correct: "an",
    placeholder: "article",
    category: "articles",
    explanation: "'Authority' can take 'an' when qualified by a defining relative clause; 'authority' starts with a vowel sound.",
  },
  {
    sentence: "They visited ___ United Kingdom and Ireland during their vacation.",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "Countries with 'kingdom', 'states', 'republic' or plural names take 'the'.",
  },
  {
    sentence: "By ___ way, have you heard about the new policy changes?",
    options: ["a", "an", "the", "no article"],
    correct: "the",
    placeholder: "article",
    category: "articles",
    explanation: "'By the way' is a fixed idiomatic expression requiring 'the'.",
  },
  {
    sentence: "He was elected as ___ president of the student council unanimously.",
    options: ["a", "an", "the", "no article"],
    correct: "no article",
    placeholder: "article",
    category: "articles",
    explanation: "No article is needed for unique titles like 'president', 'chairman', 'mayor' when referring to the position.",
  },
  {
    sentence: "I have ___ headache that just won't go away no matter what I try.",
    options: ["a", "an", "the", "no article"],
    correct: "a",
    placeholder: "article",
    category: "articles",
    explanation: "'Headache' starts with a consonant sound; the definite relative clause specifies which headache.",
  },
];

const advancedReportedSpeech: GrammarTemplate[] = [
  {
    sentence: "She inquired whether the documents ___ submitted before the deadline.",
    options: ["are", "were", "had been", "have been"],
    correct: "had been",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Perfect passive 'have been submitted' backshifts to Past Perfect passive 'had been submitted'.",
  },
  {
    sentence: "He demanded to know why he ___ about the changes.",
    options: ["isn't told", "wasn't told", "hadn't been told", "hasn't been told"],
    correct: "hadn't been told",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple passive 'wasn't told' shifts to Past Perfect passive 'hadn't been told'.",
  },
  {
    sentence: "The witness testified that she ___ the suspect leaving the building.",
    options: ["sees", "saw", "had seen", "was seeing"],
    correct: "had seen",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'saw' backshifts to Past Perfect 'had seen' in formal testimony.",
  },
  {
    sentence: "She whispered that she ___ me a secret but made me promise not to tell anyone.",
    options: ["will tell", "would tell", "told", "had told"],
    correct: "would tell",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Will tell' becomes 'would tell' in reported speech after a past reporting verb.",
  },
  {
    sentence: "He doubted whether they ___ able to finish the project on time.",
    options: ["are", "were", "would be", "had been"],
    correct: "would be",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "'Will be' changes to 'would be' when reporting doubts after a past reporting verb.",
  },
  {
    sentence: "She admitted that she ___ about resigning for months before she actually did it.",
    options: ["thinks", "thought", "had been thinking", "has been thinking"],
    correct: "had been thinking",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Perfect Continuous 'had been thinking' shows the ongoing nature before another past action.",
  },
  {
    sentence: "The official confirmed that all necessary precautions ___ prior to the launch.",
    options: ["are taken", "were taken", "had been taken", "would be taken"],
    correct: "had been taken",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple passive 'were taken' shifts to Past Perfect passive 'had been taken' in formal reports.",
  },
  {
    sentence: "He insisted that he ___ anything wrong and demanded an apology.",
    options: ["doesn't do", "didn't do", "hadn't done", "wouldn't do"],
    correct: "hadn't done",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'didn't do' backshifts to Past Perfect 'hadn't done' after 'insisted'.",
  },
  {
    sentence: "She wondered aloud what ___ of her if she hadn't met her husband.",
    options: ["becomes", "became", "had become", "would have become"],
    correct: "would have become",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Third conditional in reported speech: 'would have become' stays unchanged after 'wondered'.",
  },
  {
    sentence: "The manager pointed out that profits ___ steadily since the new strategy was implemented.",
    options: ["rise", "rose", "had been rising", "have been rising"],
    correct: "had been rising",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Present Perfect Continuous 'have been rising' backshifts to Past Perfect Continuous after a past reporting verb.",
  },
  {
    sentence: "He confided in me that he ___ the courage to ask for a raise for over a year.",
    options: ["lacks", "lacked", "had been lacking", "has lacked"],
    correct: "had been lacking",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Perfect Continuous emphasizes the duration of the state before the moment of confiding.",
  },
  {
    sentence: "She replied that she ___ the email and would respond shortly.",
    options: ["receives", "received", "had received", "has received"],
    correct: "had received",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'received' backshifts to Past Perfect 'had received' in reported speech.",
  },
  {
    sentence: "The defendant claimed that he ___ at the scene of the crime at all.",
    options: ["isn't", "wasn't", "hadn't been", "wouldn't be"],
    correct: "hadn't been",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'wasn't' shifts to Past Perfect 'hadn't been' in formal reported statements.",
  },
  {
    sentence: "He reflected that if he ___ harder at university, his career might have been very different.",
    options: ["works", "worked", "had worked", "would work"],
    correct: "had worked",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Third conditional within reported speech: Past Perfect stays the same as it's already the furthest backshift.",
  },
  {
    sentence: "She acknowledged that she ___ the risks before making the investment.",
    options: ["understands", "understood", "had understood", "would understand"],
    correct: "had understood",
    placeholder: "verb form",
    category: "reported-speech",
    explanation: "Past Simple 'understood' shifts to Past Perfect 'had understood' in reported speech with 'acknowledged'.",
  },
];

const advancedModals: GrammarTemplate[] = [
  {
    sentence: "You ___ to inform the bank before traveling abroad with your credit card.",
    options: ["must", "should", "ought", "need"],
    correct: "ought",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Ought to' expresses moral obligation or advisable action, similar to 'should' but slightly more formal.",
  },
  {
    sentence: "We ___ have rushed to the airport; the flight was delayed by three hours.",
    options: ["mustn't", "shouldn't", "needn't", "oughtn't"],
    correct: "needn't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Needn't have + past participle' means an action was done but turned out to be unnecessary.",
  },
  {
    sentence: "I ___ have brought an umbrella; it hasn't rained a single drop all day.",
    options: ["mustn't", "shouldn't", "needn't", "oughtn't"],
    correct: "needn't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Needn't have + past participle' expresses that a past action was unnecessary.",
  },
  {
    sentence: "She ___ to apologize for her behavior at the dinner party; it was quite rude.",
    options: ["must", "should", "ought", "need"],
    correct: "ought",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Ought to' is used for moral duty or what is right, especially regarding social behavior.",
  },
  {
    sentence: "You ___ have seen his face when he opened the surprise gift; it was priceless!",
    options: ["must", "should", "could", "need"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have seen' is used to express that someone missed something amazing.",
  },
  {
    sentence: "The government ___ to invest more in public transportation infrastructure.",
    options: ["must", "should", "ought", "need"],
    correct: "ought",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Ought to' expresses a strong recommendation, often used in formal or public contexts.",
  },
  {
    sentence: "We ___ have worried about the test; it turned out to be very easy.",
    options: ["mustn't", "shouldn't", "needn't", "couldn't"],
    correct: "needn't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Needn't have + past participle' shows that worrying was unnecessary because the outcome was positive.",
  },
  {
    sentence: "He ___ to be more careful with his words; some people take things too personally.",
    options: ["must", "should", "ought", "need"],
    correct: "ought",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Ought to' gives advice about what is socially or morally correct.",
  },
  {
    sentence: "You ___ have told me about the party earlier; I already made other plans.",
    options: ["must", "should", "could", "need"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have + past participle' expresses that something would have been the right thing to do.",
  },
  {
    sentence: "They ___ have booked a larger venue; half the guests had nowhere to sit.",
    options: ["must", "should", "ought", "need"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have + past participle' expresses criticism or regret about a past decision.",
  },
  {
    sentence: "She ___ to take better care of her health; she's been working nonstop for months.",
    options: ["must", "should", "ought", "need"],
    correct: "ought",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Ought to' expresses a strong personal recommendation about well-being.",
  },
  {
    sentence: "I ___ have checked the train schedule; now I'll have to wait for two hours.",
    options: ["must", "should", "could", "need"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have + past participle' expresses personal regret about not doing something.",
  },
  {
    sentence: "You ___ have cooked such an elaborate meal just for me; something simple would have been fine.",
    options: ["mustn't", "shouldn't", "needn't", "couldn't"],
    correct: "needn't",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Needn't have + past participle' politely indicates that someone's effort was appreciated but unnecessary.",
  },
  {
    sentence: "Employees ___ to report any suspicious activity to the security office immediately.",
    options: ["must", "should", "ought", "need"],
    correct: "ought",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Ought to' is used in formal policies and procedures, similar to 'should' but more authoritative.",
  },
  {
    sentence: "You ___ have seen the look on her face — she was absolutely shocked by the news.",
    options: ["must", "should", "could", "need"],
    correct: "should",
    placeholder: "modal verb",
    category: "modals",
    explanation: "'Should have seen' is an idiomatic expression meaning 'it was worth seeing' or 'you missed out'.",
  },
];

export const grammarTemplates: Record<Difficulty, Record<GrammarCategory, GrammarTemplate[]>> = {
  beginner: {
    tenses: beginnerTenses,
    prepositions: beginnerPrepositions,
    conditionals: beginnerConditionals,
    articles: beginnerArticles,
    "reported-speech": beginnerReportedSpeech,
    modals: beginnerModals,
  },
  intermediate: {
    tenses: intermediateTenses,
    prepositions: intermediatePrepositions,
    conditionals: intermediateConditionals,
    articles: intermediateArticles,
    "reported-speech": intermediateReportedSpeech,
    modals: intermediateModals,
  },
  advanced: {
    tenses: advancedTenses,
    prepositions: advancedPrepositions,
    conditionals: advancedConditionals,
    articles: advancedArticles,
    "reported-speech": advancedReportedSpeech,
    modals: advancedModals,
  },
};

export function getGrammarQuestions(
  categories: GrammarCategory[],
  difficulty: Difficulty,
  count?: number,
): GrammarTemplate[] {
  let questions: GrammarTemplate[] = [];

  for (const category of categories) {
    const diffBank = grammarTemplates[difficulty] ?? grammarTemplates.beginner;
    const templates = diffBank[category];
    if (templates) {
      questions = questions.concat(templates);
    }
  }

  for (let i = questions.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [questions[i], questions[j]] = [questions[j], questions[i]];
  }

  if (count !== undefined && count < questions.length) {
    return questions.slice(0, count);
  }

  return questions;
}
