import type { IdiomCategory, IdiomEntry } from "@/types";

export const idioms: Record<IdiomCategory, IdiomEntry[]> = {
  business: [
    {
      idiom: "think outside the box",
      meaning: "To think creatively and unconventionally, beyond the usual patterns or constraints",
      origin: "The phrase originated from a classic nine-dot puzzle used by management consultants in the 1960s-70s, where the solution required drawing lines outside the imaginary square formed by the dots.",
      example: "The marketing team needs to think outside the box if we want this campaign to stand out from competitors.",
      category: "business",
    },
    {
      idiom: "touch base",
      meaning: "To make brief contact with someone, usually to exchange information or coordinate",
      origin: "Comes from baseball terminology, where a runner must physically touch each base to be safe, which was adopted into business jargon in the mid-20th century.",
      example: "Let's touch base next week after you've had a chance to review the proposal.",
      category: "business",
    },
    {
      idiom: "move the needle",
      meaning: "To make a noticeable difference or produce a significant change in performance metrics",
      origin: "Originated from the dials and gauges on early sound equipment, machinery, and recording devices where the needle physically moved to show changes in levels.",
      example: "Our latest feature update didn't really move the needle on user engagement numbers.",
      category: "business",
    },
    {
      idiom: "low-hanging fruit",
      meaning: "The easiest tasks or goals that require minimal effort to achieve",
      origin: "Literally refers to fruit on a tree that hangs low enough to pick without climbing or using a ladder, adopted by business strategists in the 1990s.",
      example: "Before we tackle the complex integration, let's grab the low-hanging fruit and fix those simple UI bugs.",
      category: "business",
    },
    {
      idiom: "ballpark figure",
      meaning: "A rough numerical estimate, not expected to be precise",
      origin: "Comes from the space inside a baseball stadium (the ballpark), famously adopted by people trying to guess the number of spectators in the stands, the ballpark being a measure of size, implying 'in the general area'.",
      example: "Can you give me a ballpark figure for the project budget before I take it to the stakeholders?",
      category: "business",
    },
    {
      idiom: "get the ball rolling",
      meaning: "To start a process or initiate an activity",
      origin: "Likely derived from sports like soccer or football, where the game begins once the ball is set in motion; adopted into business speech by the mid-20th century.",
      example: "I'll send out the meeting invitation to get the ball rolling on the quarterly review.",
      category: "business",
    },
    {
      idiom: "back to the drawing board",
      meaning: "To start over after a plan or idea has failed",
      origin: "Originated during World War II, popularized by a 1941 New Yorker cartoon by Peter Arno showing a crashed aircraft with the caption 'Well, back to the old drawing board.'",
      example: "The client rejected all three designs, so it's back to the drawing board for us.",
      category: "business",
    },
    {
      idiom: "cutting edge",
      meaning: "The most advanced or innovative stage in development",
      origin: "Comes from the literal sharp edge of a cutting tool or blade, representing the forefront of technological or scientific advancement since the 19th century.",
      example: "Our startup is developing cutting-edge AI technology for medical imaging diagnosis.",
      category: "business",
    },
    {
      idiom: "hit the ground running",
      meaning: "To start a new role or project with great energy and immediate effectiveness",
      origin: "Military origin from airborne troops who had to start running immediately after landing to avoid being an easy target, later adopted as business terminology in the 1980s.",
      example: "We need someone who can hit the ground running and contribute to the codebase from day one.",
      category: "business",
    },
    {
      idiom: "learn the ropes",
      meaning: "To learn the basics of how something is done or how an organization operates",
      origin: "Nautical origin from the age of sail, where new sailors had to learn which rope controlled which sail on the complex rigging of sailing ships.",
      example: "It'll take a few weeks to learn the ropes, but after that you should be fully autonomous.",
      category: "business",
    },
    {
      idiom: "on the same page",
      meaning: "To be in agreement or have a shared understanding with others",
      origin: "Likely originating from choral or orchestral rehearsals where all musicians must follow the same sheet of music on the same page; adopted into corporate language in the 1970s.",
      example: "Before we present to the board, let's make sure the entire team is on the same page about our strategy.",
      category: "business",
    },
    {
      idiom: "raise the bar",
      meaning: "To set a higher standard or expectation for performance or quality",
      origin: "Comes from athletics, specifically the high jump and pole vault events where the bar is literally raised higher after each successful clearance.",
      example: "The competitor's new product has really raised the bar for what customers expect from our industry.",
      category: "business",
    },
    {
      idiom: "win-win situation",
      meaning: "A scenario where all parties benefit and no one loses",
      origin: "Popularized by Stephen Covey in his 1989 book 'The 7 Habits of Highly Effective People' as part of negotiation and conflict resolution theory.",
      example: "Partnering with the university gives us access to talent and gives students real experience — it's a win-win situation.",
      category: "business",
    },
    {
      idiom: "circle back",
      meaning: "To return to a topic or reconnect with someone at a later time",
      origin: "Emerged from American corporate culture in the 1980s-90s, likely from the physical act of circling back in a conversation flow or an airplane circling back to a destination.",
      example: "I don't have the numbers right now, but let me circle back with you tomorrow afternoon.",
      category: "business",
    },
    {
      idiom: "boil the ocean",
      meaning: "To attempt something impossibly large, complex, or overambitious",
      origin: "First recorded use in business context around the 1980s, suggesting a task as futile as trying to boil the entire ocean with a single flame.",
      example: "We don't need to boil the ocean with this redesign — let's just focus on the checkout flow for now.",
      category: "business",
    },
    {
      idiom: "core competency",
      meaning: "A defining capability or advantage that distinguishes a company from its competitors",
      origin: "Introduced by management theorists C.K. Prahalad and Gary Hamel in their 1990 Harvard Business Review article 'The Core Competence of the Corporation.'",
      example: "Software development is our core competency; we should outsource the hardware manufacturing.",
      category: "business",
    },
    {
      idiom: "push the envelope",
      meaning: "To go beyond established limits or test the boundaries of what is possible",
      origin: "Originally an aviation term from the 1940s referring to the 'flight envelope' — the technical limits of an aircraft's performance — pushing past which was considered risky.",
      example: "The R&D team continues to push the envelope on what our platform can handle in real time.",
      category: "business",
    },
    {
      idiom: "get your foot in the door",
      meaning: "To obtain an initial opportunity or entry point that may lead to future success",
      origin: "Originates from door-to-door salesmanship, where preventing the door from closing with one's foot gave the salesman a chance to make his pitch; applied to careers by the 1950s.",
      example: "The internship isn't glamorous, but it's a great way to get your foot in the door at the company.",
      category: "business",
    },
    {
      idiom: "run it up the flagpole",
      meaning: "To present an idea to gauge reactions and see if people approve",
      origin: "Comes from the US military practice of hoisting a new flag design up the pole to see how it looks and gather opinions, particularly during the flag design era of the early 1900s.",
      example: "I'm not sure the client will love this concept — let's run it up the flagpole at the meeting today.",
      category: "business",
    },
    {
      idiom: "drill down",
      meaning: "To examine something in greater detail, moving from general to specific",
      origin: "Borrowed from oil drilling terminology, where drilling goes vertically deeper into the earth, adopted as a data analysis metaphor in the computer age of the 1990s.",
      example: "Once we see the quarterly report, we'll drill down into the regional sales data to understand the trends.",
      category: "business",
    },
  ],

  everyday: [
    {
      idiom: "break the ice",
      meaning: "To initiate conversation or relieve tension in a social situation",
      origin: "Dates back to the 16th century, referring to special ice-breaking ships that cleared paths for other vessels in frozen waters, metaphorically making social navigation easier.",
      example: "The host told a funny joke to break the ice at the awkward dinner party.",
      category: "everyday",
    },
    {
      idiom: "spill the beans",
      meaning: "To reveal secret information, often accidentally",
      origin: "Thought to come from ancient Greek voting practices where beans were used as ballots — spilling the jar of beans prematurely would reveal the vote results before the official count.",
      example: "Come on, spill the beans! How did your blind date go last night?",
      category: "everyday",
    },
    {
      idiom: "hit the sack",
      meaning: "To go to bed and fall asleep",
      origin: "From the early 20th century when beds were often made from sacks stuffed with straw or hay; 'hitting' the sack meant literally flopping onto this primitive mattress after a long day.",
      example: "It's been a long week — I'm going to hit the sack early tonight.",
      category: "everyday",
    },
    {
      idiom: "piece of cake",
      meaning: "Something very easy to accomplish",
      origin: "Emerged in the 1930s from African American vernacular, likely comparing easy tasks to the enjoyment of eating cake, and was popularized during World War II by US pilots.",
      example: "The driving test was a piece of cake — I passed on my first try without a single mistake.",
      category: "everyday",
    },
    {
      idiom: "bite the bullet",
      meaning: "To endure a painful or unpleasant situation that is unavoidable",
      origin: "Originated from battlefield surgery before anesthesia, where soldiers would literally bite on a lead bullet to endure the excruciating pain of amputation and prevent biting their tongue.",
      example: "I hate going to the dentist, but I'll just have to bite the bullet and book that appointment.",
      category: "everyday",
    },
    {
      idiom: "beat around the bush",
      meaning: "To avoid addressing a topic directly or failing to get to the point",
      origin: "Stems from medieval bird hunting, where beaters would strike bushes with sticks to flush out game birds — beating around the bush was the indirect, hesitant approach rather than tackling the quarry directly.",
      example: "Stop beating around the bush and tell me whether you're resigning or not.",
      category: "everyday",
    },
    {
      idiom: "blessing in disguise",
      meaning: "Something that seems bad at first but ultimately results in something good",
      origin: "First recorded in the 18th-century English hymn writer James Hervey's works, reflecting the belief that apparent misfortune may be divine providence in hidden form.",
      example: "Losing that job was a blessing in disguise — it pushed me to start my own company.",
      category: "everyday",
    },
    {
      idiom: "call it a day",
      meaning: "To stop working or decide to end an activity",
      origin: "First documented in the early 20th century, likely from the literal sense that when a day's work was finished, one would 'call it' a completed day and head home.",
      example: "We've been debugging for six hours — let's call it a day and pick up fresh tomorrow morning.",
      category: "everyday",
    },
    {
      idiom: "cut corners",
      meaning: "To do something in the easiest, cheapest, or quickest way, often sacrificing quality",
      origin: "From the early 19th century, referring to carriages that cut across corners of roads instead of following the proper route, saving time but risking accidents or damaged wheels.",
      example: "The contractor cut corners on the renovation and now we have water leaking through the ceiling.",
      category: "everyday",
    },
    {
      idiom: "devil's advocate",
      meaning: "To argue a contrary position for the sake of debate, not because you believe it",
      origin: "Originates from the Catholic Church's canonization process, where the 'Promotor Fidei' (Promoter of the Faith) was appointed to argue against sainthood, earning the nickname 'devil's advocate' in 1587.",
      example: "Let me play devil's advocate for a moment — what if our competitor launches a similar product at half the price?",
      category: "everyday",
    },
    {
      idiom: "hit the nail on the head",
      meaning: "To be exactly right about something or to describe a situation perfectly accurately",
      origin: "Dating back to at least the 15th century, from carpentry where hitting a nail squarely on its head drives it true, while glancing blows bend the nail or miss entirely.",
      example: "You hit the nail on the head — the real problem isn't the budget, it's the timeline.",
      category: "everyday",
    },
    {
      idiom: "let the cat out of the bag",
      meaning: "To reveal a secret unintentionally",
      origin: "Likely from medieval market fraud where piglets were sold in tied sacks, and dishonest sellers would substitute a cat; if the buyer let the cat out of the bag, the deception was revealed.",
      example: "I was planning a surprise party for her, but her brother let the cat out of the bag.",
      category: "everyday",
    },
    {
      idiom: "once in a blue moon",
      meaning: "Something that happens very rarely",
      origin: "A 'blue moon' is the second full moon within a single calendar month, which occurs approximately every 2.7 years; the phrase has been used since the 16th century to denote rarity.",
      example: "I only see my college friends once in a blue moon since we all moved to different cities.",
      category: "everyday",
    },
    {
      idiom: "pull someone's leg",
      meaning: "To tease or joke with someone, trying to make them believe something untrue",
      origin: "May originate from 19th-century London street thieves who would literally pull a victim's leg to trip them before robbing them — the phrase evolved to mean a less harmful form of deception.",
      example: "Don't believe him — he's just pulling your leg about having met the Queen.",
      category: "everyday",
    },
    {
      idiom: "sit tight",
      meaning: "To wait patiently and not take action yet",
      origin: "From the 18th century, originally a horseback riding instruction to maintain a firm, steady seat without moving, which evolved into advice for staying put and being patient.",
      example: "Sit tight in the waiting room — the doctor will call your name when she's ready.",
      category: "everyday",
    },
    {
      idiom: "steal someone's thunder",
      meaning: "To take credit for someone else's idea or to upstage them",
      origin: "Comes from the early 18th-century playwright John Dennis, who invented a device to mimic thunder for his play; after the play flopped, he heard his thunder effect used in someone else's production and exclaimed they had stolen his thunder.",
      example: "I was about to announce the promotion, but she stole my thunder by revealing it at lunch.",
      category: "everyday",
    },
    {
      idiom: "take with a grain of salt",
      meaning: "To view something with skepticism or not take it entirely at face value",
      origin: "Traced to Pliny the Elder's 'Naturalis Historia' (77 AD), where he described an antidote recipe that included a grain of salt — implying that taking something with salt made it easier to swallow.",
      example: "I'd take his financial advice with a grain of salt — he's not exactly the best with money himself.",
      category: "everyday",
    },
    {
      idiom: "under the weather",
      meaning: "Feeling slightly unwell or in low spirits",
      origin: "Maritime origin from the 19th century: when sailors felt seasick, they were sent below deck to be 'under the weather bow' — the side of the ship receiving the worst of the wind and waves.",
      example: "I won't make it to the meeting today — I'm feeling a bit under the weather.",
      category: "everyday",
    },
    {
      idiom: "when pigs fly",
      meaning: "Something that will never happen or is impossible",
      origin: "Dating back to the 1600s Scottish proverb era, with the earliest recorded English use in John Withal's dictionary; the absurd mental image of pigs soaring through the sky reinforces the impossibility.",
      example: "He'll clean his apartment without being asked when pigs fly.",
      category: "everyday",
    },
    {
      idiom: "bark up the wrong tree",
      meaning: "To pursue a mistaken or misguided course of action or blame the wrong person",
      origin: "Comes from 19th-century American raccoon hunting with dogs, where a dog might bark at the base of one tree while the raccoon had already escaped to another.",
      example: "If you think I'm the one who ate your leftovers, you're barking up the wrong tree — ask Dave.",
      category: "everyday",
    },
  ],

  "phrasal-verbs": [
    {
      idiom: "look up to",
      meaning: "To admire and respect someone",
      origin: "The physical sense of literally looking upward at someone taller or on a pedestal evolved into a metaphor for admiration by the 17th century.",
      example: "I've always looked up to my grandmother — she built a business from nothing with three kids at home.",
      category: "phrasal-verbs",
    },
    {
      idiom: "come across",
      meaning: "To find or encounter something unexpectedly; also to give a particular impression",
      origin: "Emerged from Middle English as a combination of 'come' and 'across,' originally describing physically traversing or encountering something; the impression sense developed in the 19th century.",
      example: "I came across an old photo album while cleaning the attic last weekend.",
      category: "phrasal-verbs",
    },
    {
      idiom: "put off",
      meaning: "To postpone or delay something; also to discourage or repel someone",
      origin: "Dating from the 14th century, originally meaning to remove or discard clothing, later extending to putting things away for a later time.",
      example: "We should stop putting off the annual report — the deadline is only three days away.",
      category: "phrasal-verbs",
    },
    {
      idiom: "get along with",
      meaning: "To have a friendly and harmonious relationship with someone",
      origin: "The sense of 'getting along' meaning to progress or manage developed by the 18th century, with the interpersonal relationship nuance solidifying in the 19th century.",
      example: "I get along with my new colleagues really well — the team has great chemistry.",
      category: "phrasal-verbs",
    },
    {
      idiom: "run out of",
      meaning: "To exhaust the supply of something",
      origin: "From the 15th century, where 'run' was used to describe the motion of a river draining or flowing out until empty, eventually applied to any depleting resource.",
      example: "Halfway through the recipe I realized we had run out of flour.",
      category: "phrasal-verbs",
    },
    {
      idiom: "bring up",
      meaning: "To raise a topic for discussion; also to raise a child",
      origin: "Emerged in the 14th century from the literal sense of physically lifting or carrying something upward, extending to metaphorical elevation of subjects and children.",
      example: "I hate to bring up the budget issue again, but we're already over our monthly limit.",
      category: "phrasal-verbs",
    },
    {
      idiom: "carry out",
      meaning: "To execute, implement, or complete a task or plan",
      origin: "From the 15th century, originally referring to the physical act of carrying something out of a place, evolving to mean seeing an action through to its conclusion.",
      example: "The research team carried out extensive tests before releasing the software update.",
      category: "phrasal-verbs",
    },
    {
      idiom: "drop off",
      meaning: "To deliver someone or something somewhere; also to fall asleep or decrease",
      origin: "From the early 19th century, originally describing passengers dropping from a moving vehicle (a carriage), which evolved into the modern sense of delivering someone.",
      example: "I'll drop the kids off at school on my way to the office.",
      category: "phrasal-verbs",
    },
    {
      idiom: "figure out",
      meaning: "To solve, understand, or discover something through reasoning",
      origin: "American English origin from the early 19th century, combining 'figure' in the mathematical sense with 'out' suggesting resolution or completion.",
      example: "It took me an hour to figure out why the API was returning those cryptic error codes.",
      category: "phrasal-verbs",
    },
    {
      idiom: "give up",
      meaning: "To stop trying, surrender, or abandon a habit",
      origin: "Dates to the 12th century Old English 'giefan up,' originally meaning to hand over or surrender to a higher authority or enemy.",
      example: "After applying to 50 companies with no response, I almost gave up — then I got the dream offer.",
      category: "phrasal-verbs",
    },
    {
      idiom: "hold on",
      meaning: "To wait for a short time; to grip something tightly",
      origin: "From the 13th century, the sense of maintaining a physical grip extended by the 19th century to the metaphorical sense of maintaining patience or waiting.",
      example: "Hold on a second, let me find the document before we continue the call.",
      category: "phrasal-verbs",
    },
    {
      idiom: "look forward to",
      meaning: "To feel excited and eager about something that is going to happen",
      origin: "From the 16th century, deriving from the physical act of leaning forward to see something approaching in the distance, becoming a metaphor for positive anticipation.",
      example: "I'm really looking forward to the concert next month — I've been waiting to see this band for years.",
      category: "phrasal-verbs",
    },
    {
      idiom: "make up",
      meaning: "To invent a story or excuse; to reconcile after a disagreement; to constitute",
      origin: "From the 14th century with the sense of composing or forming something, with the reconciliation meaning emerging in the 17th century from the idea of repairing a broken relationship.",
      example: "After a week of not talking, my sister and I finally made up over coffee yesterday.",
      category: "phrasal-verbs",
    },
    {
      idiom: "pick up",
      meaning: "To collect someone or something; to learn a skill informally; to notice or detect",
      origin: "From the 14th century literal sense of lifting from the ground, which by the 19th century had expanded to dozens of meanings including transportation and informal learning.",
      example: "I'll pick you up at seven, so be ready when I arrive.",
      category: "phrasal-verbs",
    },
    {
      idiom: "point out",
      meaning: "To indicate, highlight, or draw attention to something",
      origin: "From the 15th century, originating literally as pointing a finger outward toward something, then generalizing to verbal indication.",
      example: "She pointed out several errors in the report that everyone else had overlooked.",
      category: "phrasal-verbs",
    },
    {
      idiom: "set up",
      meaning: "To establish, arrange, or organize something; to frame someone",
      origin: "From the 13th century, originally meaning to place in an upright or elevated position, with additional meanings of establishment and entrapment developing over centuries.",
      example: "We need to set up the development environment before we can start writing any code.",
      category: "phrasal-verbs",
    },
    {
      idiom: "take off",
      meaning: "To remove something; for an aircraft to leave the ground; to become successful very quickly",
      origin: "From the 14th century sense of removing clothing; the aviation meaning arrived in the 20th century, and the success sense followed shortly after.",
      example: "The startup really took off after their product was featured on a popular tech blog.",
      category: "phrasal-verbs",
    },
    {
      idiom: "turn down",
      meaning: "To reject or refuse an offer or proposal",
      origin: "From the 17th century, originally referring to folding down the corner of a page or turning a playing card face down, signaling rejection.",
      example: "The candidate turned down the job offer because the salary didn't meet her expectations.",
      category: "phrasal-verbs",
    },
    {
      idiom: "work out",
      meaning: "To exercise; to solve a problem; to result in a successful outcome",
      origin: "From the 16th century in the sense of working something out through effort; the exercise meaning emerged in the early 20th century with the physical culture movement.",
      example: "I hope your new living arrangement works out — having roommates can be challenging.",
      category: "phrasal-verbs",
    },
    {
      idiom: "break down",
      meaning: "To stop functioning mechanically or emotionally; to analyze into components",
      origin: "From the 14th century meaning to demolish utterly; the mechanical failure sense emerged in the 19th century with industrialization, and the analytical sense followed in the 20th century.",
      example: "Let's break down the project into smaller milestones so we can track progress more easily.",
      category: "phrasal-verbs",
    },
  ],

  proverbs: [
    {
      idiom: "actions speak louder than words",
      meaning: "What people actually do is more important and revealing than what they say they will do",
      origin: "First recorded in English in John Pym's parliamentary speech of 1628, though similar sentiments appear in ancient Greek writings; Abraham Lincoln later popularized it in the American context.",
      example: "He keeps promising to change, but actions speak louder than words — I need to see actual effort.",
      category: "proverbs",
    },
    {
      idiom: "don't count your chickens before they hatch",
      meaning: "Don't assume success or make plans based on outcomes that haven't happened yet",
      origin: "Traced to Aesop's fable of the milkmaid who balanced a pail of milk on her head while daydreaming about the eggs she'd buy, before spilling everything; the phrase itself first appeared in print in the 16th century.",
      example: "The deal isn't signed yet — don't count your chickens before they hatch.",
      category: "proverbs",
    },
    {
      idiom: "every cloud has a silver lining",
      meaning: "Even the worst situations have some hidden positive aspect",
      origin: "Coined by John Milton in his 1634 poem 'Comus,' where he described a cloud turned inside out revealing its silver lining illuminated by the sun.",
      example: "I was devastated when the trip was canceled, but every cloud has a silver lining — I used the refund to redecorate my apartment.",
      category: "proverbs",
    },
    {
      idiom: "a picture is worth a thousand words",
      meaning: "A visual representation conveys complex information more effectively than a verbal description",
      origin: "Often attributed to early 20th-century American advertising, specifically a 1921 advertisement by Fred R. Barnard promoting the use of images in streetcar advertising.",
      example: "I could describe the sunset forever, but a picture is worth a thousand words — just look at this photo.",
      category: "proverbs",
    },
    {
      idiom: "better late than never",
      meaning: "It is preferable to do something after the expected time than not to do it at all",
      origin: "Found in Geoffrey Chaucer's 'The Canterbury Tales' (1386), but the sentiment traces back to the ancient Roman historian Livy, who recorded it in his 'History of Rome.'",
      example: "I finally graduated at 35 — better late than never, right?",
      category: "proverbs",
    },
    {
      idiom: "birds of a feather flock together",
      meaning: "People with similar interests, character, or backgrounds tend to associate with one another",
      origin: "Dates back to at least the mid-16th century, appearing in William Turner's religious text 'The Rescuing of Romish Fox' from 1545.",
      example: "It's no surprise those three are best friends — birds of a feather flock together.",
      category: "proverbs",
    },
    {
      idiom: "don't judge a book by its cover",
      meaning: "Don't form an opinion about someone or something based solely on outward appearance",
      origin: "First appeared in the mid-19th century as publishing became mass-market and book covers became decorative; the phrase gained popularity in the early 20th century.",
      example: "The restaurant looks shabby from the outside, but don't judge a book by its cover — the food is incredible.",
      category: "proverbs",
    },
    {
      idiom: "fortune favors the bold",
      meaning: "Those who take brave, decisive action are the ones most likely to succeed",
      origin: "Originally from the Latin 'audentis Fortuna iuvat' from Virgil's 'Aeneid' (19 BC), where fortune aids those who dare.",
      example: "I was nervous about pitching to the investor, but fortune favors the bold — and he loved the idea.",
      category: "proverbs",
    },
    {
      idiom: "honesty is the best policy",
      meaning: "Being truthful is ultimately the most advantageous approach in any situation",
      origin: "First recorded in English by Sir Edwin Sandys in his 1599 writings on European religious policy, though the concept appears in Aesop's fables centuries earlier.",
      example: "Just tell the client the truth about the delay — honesty is the best policy.",
      category: "proverbs",
    },
    {
      idiom: "if it ain't broke, don't fix it",
      meaning: "If something is working adequately well, leave it alone rather than risk breaking it with unnecessary changes",
      origin: "Popularized in the 1970s by American government official Bert Lance during a Congressional hearing, though the sentiment is older.",
      example: "The current login system works perfectly — if it ain't broke, don't fix it.",
      category: "proverbs",
    },
    {
      idiom: "necessity is the mother of invention",
      meaning: "The need for something drives the creation of new solutions and ideas",
      origin: "Traces to Plato's 'Republic' (circa 375 BC), though the exact English phrasing first appeared in Richard Franck's 1658 travel writings.",
      example: "They built that water filtration system because there was no clean water source nearby — necessity is the mother of invention.",
      category: "proverbs",
    },
    {
      idiom: "no pain, no gain",
      meaning: "Achieving anything worthwhile requires hardship, effort, or sacrifice",
      origin: "First recorded in the early 17th century by Robert Herrick; gained modern prominence in the 1980s fitness boom as a gym motivational slogan.",
      example: "Learning to code was brutal for the first six months, but no pain, no gain.",
      category: "proverbs",
    },
    {
      idiom: "practice makes perfect",
      meaning: "Consistent repetition of an activity leads to mastery and improvement",
      origin: "From the Latin 'uses promptos facit' recorded in the 16th century, the English version appeared shortly after and has been an educational staple ever since.",
      example: "I know public speaking terrifies you, but practice makes perfect — give one more rehearsal tonight.",
      category: "proverbs",
    },
    {
      idiom: "the early bird catches the worm",
      meaning: "Those who act promptly and arrive first gain the advantage",
      origin: "First recorded in William Camden's 1605 collection of English proverbs, with the literal observation that birds waking earliest find the most worms to eat.",
      example: "Tickets go on sale at 6 AM — the early bird catches the worm, so set your alarm.",
      category: "proverbs",
    },
    {
      idiom: "too many cooks spoil the broth",
      meaning: "When too many people are involved in a task, the quality of the result suffers",
      origin: "Dating back to the 16th century, this proverb was originally about soup preparation where too many hands adding ingredients ruin the flavor — Sir Arthur Conan Doyle referenced it in his Sherlock Holmes stories.",
      example: "The design team has grown to fifteen people — too many cooks spoil the broth, so let's narrow it to three decision-makers.",
      category: "proverbs",
    },
    {
      idiom: "when in Rome, do as the Romans do",
      meaning: "When visiting a foreign place, adapt your behavior to match local customs",
      origin: "Attributed to St. Ambrose (4th century), who advised St. Augustine that when in Rome he should follow the Roman practice of fasting on Saturday rather than his own custom.",
      example: "I'm not used to eating dinner at 10 PM, but when in Rome, do as the Romans do.",
      category: "proverbs",
    },
    {
      idiom: "you can't have your cake and eat it too",
      meaning: "You cannot have two incompatible things or enjoy both of two mutually exclusive alternatives",
      origin: "First recorded in English in John Heywood's 1546 proverb collection, originally phrased as 'Would you both eat your cake and have your cake?' making the logical impossibility clearer.",
      example: "You want a high-paying job but also unlimited free time — you can't have your cake and eat it too.",
      category: "proverbs",
    },
    {
      idiom: "absence makes the heart grow fonder",
      meaning: "Being separated from someone increases affection and appreciation for them",
      origin: "First known appearance in the 1602 English poem 'The Tragical History of Pyramus and Thisbe' by Thomas Haynes, though similar sentiments appear in ancient Roman poetry by Sextus Propertius.",
      example: "After six months abroad, I miss home more than ever — absence makes the heart grow fonder.",
      category: "proverbs",
    },
    {
      idiom: "the grass is always greener on the other side",
      meaning: "People tend to believe that others' circumstances are better than their own, even when that isn't true",
      origin: "Rooted in ancient Greek poetry by Ovid, the modern English version crystallized in the 20th century as a commentary on human nature's dissatisfaction with its own lot.",
      example: "She left her great job for a competitor and regrets it — the grass is always greener on the other side.",
      category: "proverbs",
    },
    {
      idiom: "don't put all your eggs in one basket",
      meaning: "Don't risk everything on a single venture or dependency",
      origin: "First recorded in Miguel de Cervantes' 'Don Quixote' (1605) in Spanish, and appeared in English by the early 17th century; became a fundamental principle of investment diversification.",
      example: "Apply to at least ten universities — don't put all your eggs in one basket with just your dream school.",
      category: "proverbs",
    },
  ],
};

export function getRandomIdioms(count?: number, category?: IdiomCategory): IdiomEntry[] {
  const pool = category ? idioms[category] : Object.values(idioms).flat();
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  const limit = count ?? 10;
  return shuffled.slice(0, Math.min(limit, shuffled.length));
}

export function getDailyIdiom(): IdiomEntry {
  const allIdioms = Object.values(idioms).flat();
  const today = new Date();
  const dateKey = `${today.getFullYear()}-${today.getMonth()}-${today.getDate()}`;

  let hash = 0;
  for (let i = 0; i < dateKey.length; i++) {
    const char = dateKey.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }

  const index = Math.abs(hash) % allIdioms.length;
  return allIdioms[index];
}
