import type { Difficulty, WordEntry } from "@/types";

const beginnerWords: WordEntry[] = [
  {
    word: "apple",
    translation: "яблоко",
    definition: "A round fruit with red, yellow, or green skin and firm white flesh",
    example: "She ate an apple for lunch.",
    transcription: "[ˈæpəl]",
    synonyms: ["fruit"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "bread",
    translation: "хлеб",
    definition: "A food made from flour, water, and yeast mixed together and baked",
    example: "I bought fresh bread from the bakery.",
    transcription: "[bred]",
    synonyms: ["loaf", "baked goods"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "chicken",
    translation: "курица",
    definition: "A type of bird kept on a farm for its eggs or its meat",
    example: "We had roast chicken for dinner.",
    transcription: "[ˈtʃɪkɪn]",
    synonyms: ["poultry", "fowl"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "milk",
    translation: "молоко",
    definition: "A white liquid produced by female mammals to feed their young",
    example: "He drinks a glass of milk every morning.",
    transcription: "[mɪlk]",
    synonyms: ["dairy", "cream"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "rice",
    translation: "рис",
    definition: "Small white or brown grains from a plant grown in wet fields, eaten as food",
    example: "Rice is a staple food in many Asian countries.",
    transcription: "[raɪs]",
    synonyms: ["grain", "cereal"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "soup",
    translation: "суп",
    definition: "A hot liquid food made by boiling meat, vegetables, or other ingredients in water",
    example: "My grandmother makes the best chicken soup.",
    transcription: "[suːp]",
    synonyms: ["broth", "stew"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "broth",
    translation: "бульон",
    definition: "A thin, clear soup made by boiling meat and vegetables in water",
    example: "She made a warm chicken broth for the cold winter evening.",
    transcription: "[brɒθ]",
    synonyms: ["stock", "bouillon", "consommé"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "salad",
    translation: "салат",
    definition: "A cold dish of raw vegetables mixed together, often with a dressing",
    example: "I ordered a green salad with my meal.",
    transcription: "[ˈsæləd]",
    synonyms: ["mixed greens"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "cheese",
    translation: "сыр",
    definition: "A solid food made from milk, usually yellow or white in color",
    example: "Would you like some cheese on your sandwich?",
    transcription: "[tʃiːz]",
    synonyms: ["dairy product", "fromage"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "egg",
    translation: "яйцо",
    definition: "An oval object produced by birds and other creatures, eaten as food",
    example: "Can you fry an egg for breakfast?",
    transcription: "[eɡ]",
    synonyms: ["ovum"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "sugar",
    translation: "сахар",
    definition: "A sweet substance used to make food and drinks taste sweet",
    example: "Do you take sugar in your coffee?",
    transcription: "[ˈʃʊɡər]",
    synonyms: ["sweetener", "sucrose"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "airport",
    translation: "аэропорт",
    definition: "A place where aircraft regularly take off and land, with buildings for passengers",
    example: "We arrived at the airport two hours before the flight.",
    transcription: "[ˈeəpɔːrt]",
    synonyms: ["terminal", "airfield", "airstrip"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "ticket",
    translation: "билет",
    definition: "A piece of paper or an electronic record that allows you to travel or enter a place",
    example: "I booked my plane ticket online.",
    transcription: "[ˈtɪkɪt]",
    synonyms: ["pass", "voucher"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "hotel",
    translation: "отель",
    definition: "A building where people pay to stay in rooms for a short time",
    example: "They stayed at a nice hotel near the beach.",
    transcription: "[hoʊˈtel]",
    synonyms: ["inn", "motel", "lodging"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "train",
    translation: "поезд",
    definition: "A long vehicle that travels on rails, carrying passengers or goods",
    example: "The train to London leaves at three o'clock.",
    transcription: "[treɪn]",
    synonyms: ["railway", "locomotive"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "map",
    translation: "карта",
    definition: "A drawing that shows the roads, rivers, and places in a particular area",
    example: "Can you look at the map and find the museum?",
    transcription: "[mæp]",
    synonyms: ["atlas", "chart", "guide"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "bus",
    translation: "автобус",
    definition: "A large motor vehicle that carries passengers by road",
    example: "I take the bus to work every day.",
    transcription: "[bʌs]",
    synonyms: ["coach", "shuttle"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "passport",
    translation: "паспорт",
    definition: "An official document that shows who you are and allows you to travel abroad",
    example: "Don't forget to bring your passport to the airport.",
    transcription: "[ˈpæspɔːrt]",
    synonyms: ["travel document", "ID"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "beach",
    translation: "пляж",
    definition: "An area of sand or small stones beside the sea or a lake",
    example: "We spent the whole day relaxing on the beach.",
    transcription: "[biːtʃ]",
    synonyms: ["seashore", "coast", "shore"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "suitcase",
    translation: "чемодан",
    definition: "A case with a handle used for carrying clothes and possessions when travelling",
    example: "She packed her suitcase the night before the trip.",
    transcription: "[ˈsuːtkeɪs]",
    synonyms: ["luggage", "baggage", "travel bag"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "computer",
    translation: "компьютер",
    definition: "An electronic machine that stores and processes data using programs",
    example: "I use my computer for work and gaming.",
    transcription: "[kəmˈpjuːtər]",
    synonyms: ["PC", "desktop", "machine"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "phone",
    translation: "телефон",
    definition: "An electronic device used for talking to people over long distances",
    example: "My phone rang while I was in the meeting.",
    transcription: "[foʊn]",
    synonyms: ["telephone", "mobile", "cellphone"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "internet",
    translation: "интернет",
    definition: "The global system of connected computers that allows people to share information",
    example: "The internet has changed the way we communicate.",
    transcription: "[ˈɪntərnet]",
    synonyms: ["web", "net", "online"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "screen",
    translation: "экран",
    definition: "The flat surface on a computer, phone, or TV where pictures and words appear",
    example: "He stared at the computer screen for hours.",
    transcription: "[skriːn]",
    synonyms: ["display", "monitor"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "email",
    translation: "электронная почта",
    definition: "A system for sending messages electronically from one computer to another",
    example: "I'll send you the documents by email.",
    transcription: "[ˈiːmeɪl]",
    synonyms: ["electronic mail", "message"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "camera",
    translation: "камера",
    definition: "A device used to take photographs or record moving images",
    example: "She used her new camera to take pictures at the party.",
    transcription: "[ˈkæmərə]",
    synonyms: ["photo device", "video recorder"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "website",
    translation: "веб-сайт",
    definition: "A place on the internet where you can find information about something",
    example: "The company launched a new website last week.",
    transcription: "[ˈwebsaɪt]",
    synonyms: ["site", "webpage", "portal"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "happy",
    translation: "счастливый",
    definition: "Feeling or showing pleasure and satisfaction",
    example: "The children looked happy playing in the garden.",
    transcription: "[ˈhæpi]",
    synonyms: ["joyful", "glad", "pleased", "delighted"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "sad",
    translation: "грустный",
    definition: "Feeling unhappy or showing sorrow",
    example: "He felt sad after his best friend moved away.",
    transcription: "[sæd]",
    synonyms: ["unhappy", "sorrowful", "upset"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "angry",
    translation: "злой",
    definition: "Having a strong feeling of annoyance or displeasure",
    example: "My father was angry when I broke the window.",
    transcription: "[ˈæŋɡri]",
    synonyms: ["mad", "furious", "irritated", "annoyed"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "afraid",
    translation: "испуганный",
    definition: "Feeling fear or worry about something that might happen",
    example: "She is afraid of the dark.",
    transcription: "[əˈfreɪd]",
    synonyms: ["scared", "frightened", "fearful"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "love",
    translation: "любовь",
    definition: "A very strong feeling of affection for someone or something",
    example: "A mother's love for her child is unconditional.",
    transcription: "[lʌv]",
    synonyms: ["affection", "devotion", "adoration", "passion"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "surprised",
    translation: "удивлённый",
    definition: "Feeling shocked or amazed by something unexpected",
    example: "She was surprised by the birthday party her friends organized.",
    transcription: "[sərˈpraɪzd]",
    synonyms: ["astonished", "amazed", "shocked"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "tired",
    translation: "уставший",
    definition: "Needing rest or sleep because you have used a lot of energy",
    example: "I was so tired after working all day.",
    transcription: "[ˈtaɪərd]",
    synonyms: ["exhausted", "weary", "fatigued"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "excited",
    translation: "взволнованный",
    definition: "Feeling very happy and enthusiastic about something",
    example: "The children are excited about going to the zoo.",
    transcription: "[ɪkˈsaɪtɪd]",
    synonyms: ["thrilled", "eager", "enthusiastic"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "money",
    translation: "деньги",
    definition: "Coins and paper notes used to buy things",
    example: "He saved his money to buy a new bicycle.",
    transcription: "[ˈmʌni]",
    synonyms: ["cash", "funds", "currency"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "job",
    translation: "работа",
    definition: "Regular work that someone does to earn money",
    example: "She found a new job as a teacher.",
    transcription: "[dʒɒb]",
    synonyms: ["occupation", "profession", "work", "position"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "shop",
    translation: "магазин",
    definition: "A place where goods are sold to customers",
    example: "I need to go to the shop to buy milk.",
    transcription: "[ʃɒp]",
    synonyms: ["store", "market", "retailer"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "bank",
    translation: "банк",
    definition: "A place where people keep their money and get loans",
    example: "I have to visit the bank to open a new account.",
    transcription: "[bæŋk]",
    synonyms: ["financial institution", "lender"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "price",
    translation: "цена",
    definition: "The amount of money that you pay to buy something",
    example: "The price of petrol has gone up again.",
    transcription: "[praɪs]",
    synonyms: ["cost", "value", "charge", "fee"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "sell",
    translation: "продавать",
    definition: "To give something to someone in exchange for money",
    example: "They sell fresh vegetables at the market.",
    transcription: "[sel]",
    synonyms: ["vend", "trade", "retail"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "company",
    translation: "компания",
    definition: "A business organization that makes or sells goods or services",
    example: "She works for a large technology company.",
    transcription: "[ˈkʌmpəni]",
    synonyms: ["firm", "business", "corporation", "enterprise"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "hospital",
    translation: "больница",
    definition: "A place where sick or injured people receive medical treatment",
    example: "He was taken to the hospital after the accident.",
    transcription: "[ˈhɒspɪtəl]",
    synonyms: ["medical center", "clinic", "infirmary"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "doctor",
    translation: "врач",
    definition: "A person whose job is to treat people who are sick or injured",
    example: "The doctor prescribed some medicine for my cough.",
    transcription: "[ˈdɒktər]",
    synonyms: ["physician", "MD", "medical practitioner", "GP"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "medicine",
    translation: "лекарство",
    definition: "A substance used to treat or prevent illness",
    example: "Take this medicine three times a day after meals.",
    transcription: "[ˈmedɪsɪn]",
    synonyms: ["medication", "drug", "remedy"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "pain",
    translation: "боль",
    definition: "An unpleasant physical feeling caused by injury or illness",
    example: "He felt a sharp pain in his back.",
    transcription: "[peɪn]",
    synonyms: ["ache", "discomfort", "soreness", "agony"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "sick",
    translation: "больной",
    definition: "Not feeling well or suffering from an illness",
    example: "She stayed home because she felt sick.",
    transcription: "[sɪk]",
    synonyms: ["ill", "unwell", "unhealthy"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "diet",
    translation: "диета",
    definition: "The food that a person usually eats",
    example: "A balanced diet is important for good health.",
    transcription: "[ˈdaɪət]",
    synonyms: ["nutrition", "food regimen", "eating plan"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "exercise",
    translation: "упражнение",
    definition: "Physical activity done to stay healthy and strong",
    example: "Regular exercise helps prevent many health problems.",
    transcription: "[ˈeksərsaɪz]",
    synonyms: ["workout", "training", "physical activity"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "sleep",
    translation: "сон",
    definition: "The natural state of rest when your eyes are closed and your body is inactive",
    example: "Most adults need about eight hours of sleep.",
    transcription: "[sliːp]",
    synonyms: ["rest", "slumber", "doze"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "school",
    translation: "школа",
    definition: "A place where children go to learn and study",
    example: "My daughter started school at the age of six.",
    transcription: "[skuːl]",
    synonyms: ["educational institution", "academy", "college"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "teacher",
    translation: "учитель",
    definition: "A person whose job is to teach students in a school",
    example: "The teacher explained the lesson clearly.",
    transcription: "[ˈtiːtʃər]",
    synonyms: ["educator", "instructor", "tutor", "professor"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "book",
    translation: "книга",
    definition: "A set of printed pages fastened together inside a cover, containing written information",
    example: "She is reading an interesting book about history.",
    transcription: "[bʊk]",
    synonyms: ["volume", "tome", "publication", "text"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "student",
    translation: "студент",
    definition: "A person who is learning at a school, college, or university",
    example: "The students worked hard for their final exams.",
    transcription: "[ˈstuːdənt]",
    synonyms: ["pupil", "learner", "scholar"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "exam",
    translation: "экзамен",
    definition: "A formal test of a person's knowledge or skill in a subject",
    example: "I have an important math exam tomorrow.",
    transcription: "[ɪɡˈzæm]",
    synonyms: ["test", "assessment", "evaluation"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "homework",
    translation: "домашнее задание",
    definition: "Schoolwork that students must do at home",
    example: "The children have a lot of homework this weekend.",
    transcription: "[ˈhoʊmwɜːrk]",
    synonyms: ["assignment", "schoolwork", "tasks"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "pencil",
    translation: "карандаш",
    definition: "A thin wooden tool with a graphite center used for writing and drawing",
    example: "She sharpened her pencil before the test.",
    transcription: "[ˈpensəl]",
    synonyms: ["writing tool", "graphite stick"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "dictionary",
    translation: "словарь",
    definition: "A book that lists words and explains what they mean",
    example: "I looked up the word in the dictionary.",
    transcription: "[ˈdɪkʃəneri]",
    synonyms: ["lexicon", "wordbook", "glossary"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "lesson",
    translation: "урок",
    definition: "A period of time when a teacher teaches students a subject",
    example: "Our English lesson starts at nine o'clock.",
    transcription: "[ˈlesən]",
    synonyms: ["class", "session", "lecture", "tutorial"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "rain",
    translation: "дождь",
    definition: "Water that falls in drops from clouds in the sky",
    example: "The rain started falling heavily during our walk.",
    transcription: "[reɪn]",
    synonyms: ["rainfall", "precipitation", "shower"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "tree",
    translation: "дерево",
    definition: "A tall plant with a trunk, branches, and leaves that lives for many years",
    example: "The children climbed the old oak tree.",
    transcription: "[triː]",
    synonyms: ["plant", "shrub"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "animal",
    translation: "животное",
    definition: "A living creature that is not a plant, such as a dog, cat, or bird",
    example: "The zoo has many different kinds of animals.",
    transcription: "[ˈænɪməl]",
    synonyms: ["creature", "beast", "living thing"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "sun",
    translation: "солнце",
    definition: "The bright star that shines in the sky during the day and gives heat and light",
    example: "The sun came out after the storm.",
    transcription: "[sʌn]",
    synonyms: ["star", "sunlight"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "flower",
    translation: "цветок",
    definition: "The colored part of a plant that produces seeds and often smells nice",
    example: "He gave her a bunch of red flowers.",
    transcription: "[ˈflaʊər]",
    synonyms: ["bloom", "blossom", "petal"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "river",
    translation: "река",
    definition: "A long, natural flow of water that goes across land to the sea",
    example: "They went swimming in the river on a hot day.",
    transcription: "[ˈrɪvər]",
    synonyms: ["stream", "waterway", "creek", "brook"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "mountain",
    translation: "гора",
    definition: "A very high hill, often with rocks near the top",
    example: "We climbed the mountain and enjoyed the beautiful view.",
    transcription: "[ˈmaʊntən]",
    synonyms: ["peak", "summit", "hill"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "sky",
    translation: "небо",
    definition: "The space above the earth that you can see when you look up",
    example: "The sky was clear and full of stars.",
    transcription: "[skaɪ]",
    synonyms: ["heavens", "air", "atmosphere"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "bird",
    translation: "птица",
    definition: "An animal with wings and feathers that can usually fly",
    example: "A beautiful bird sang outside my window.",
    transcription: "[bɜːrd]",
    synonyms: ["fowl", "songbird", "avian"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "forest",
    translation: "лес",
    definition: "A large area of land covered with trees and plants",
    example: "They got lost while hiking in the forest.",
    transcription: "[ˈfɒrɪst]",
    synonyms: ["woods", "woodland", "jungle"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "family",
    translation: "семья",
    definition: "A group of people who are related to each other, especially parents and children",
    example: "She has a large family with three brothers and two sisters.",
    transcription: "[ˈfæməli]",
    synonyms: ["relatives", "kin", "household", "clan"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "house",
    translation: "дом",
    definition: "A building where people live, usually for one family",
    example: "They bought a new house with a large garden.",
    transcription: "[haʊs]",
    synonyms: ["home", "residence", "dwelling"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "car",
    translation: "машина",
    definition: "A vehicle with four wheels and an engine that people drive on roads",
    example: "He drives his car to work every day.",
    transcription: "[kɑːr]",
    synonyms: ["automobile", "vehicle", "motor"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "clothes",
    translation: "одежда",
    definition: "Items such as shirts, trousers, and dresses that people wear",
    example: "She bought new clothes for the party.",
    transcription: "[kloʊðz]",
    synonyms: ["garments", "attire", "apparel", "outfit"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "friend",
    translation: "друг",
    definition: "A person you know well and like spending time with",
    example: "My best friend and I have known each other since childhood.",
    transcription: "[frend]",
    synonyms: ["companion", "buddy", "pal", "mate"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "kitchen",
    translation: "кухня",
    definition: "A room where food is prepared and cooked",
    example: "She was cooking dinner in the kitchen.",
    transcription: "[ˈkɪtʃɪn]",
    synonyms: ["cookhouse", "galley"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "morning",
    translation: "утро",
    definition: "The early part of the day, from sunrise until noon",
    example: "I like to go jogging in the morning.",
    transcription: "[ˈmɔːrnɪŋ]",
    synonyms: ["dawn", "daybreak", "sunrise"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "watch",
    translation: "часы",
    definition: "A small clock worn on the wrist or carried in a pocket",
    example: "He looked at his watch and realized he was late.",
    transcription: "[wɒtʃ]",
    synonyms: ["timepiece", "wristwatch", "chronometer"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "clean",
    translation: "чистый",
    definition: "Not dirty, with no marks or stains",
    example: "Please keep your room clean.",
    transcription: "[kliːn]",
    synonyms: ["tidy", "spotless", "neat", "immaculate"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "bed",
    translation: "кровать",
    definition: "A piece of furniture that people sleep on",
    example: "It's time to go to bed.",
    transcription: "[bed]",
    synonyms: ["bunk", "mattress", "cot"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "door",
    translation: "дверь",
    definition: "A flat panel that opens and closes to let people in or out of a room or building",
    example: "Please close the door when you leave.",
    transcription: "[dɔːr]",
    synonyms: ["entrance", "gateway", "portal", "entry"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "window",
    translation: "окно",
    definition: "An opening in a wall with glass that lets in light and air",
    example: "She opened the window to let in some fresh air.",
    transcription: "[ˈwɪndoʊ]",
    synonyms: ["pane", "aperture", "opening"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "balcony",
    translation: "балкон",
    definition: "A platform enclosed by a wall or railing on the outside of a building",
    example: "We had breakfast on the balcony with a lovely view of the city.",
    transcription: "[ˈbælkəni]",
    synonyms: ["terrace", "veranda", "gallery"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "cozy",
    translation: "уютный",
    definition: "Giving a feeling of comfort, warmth, and relaxation",
    example: "The living room felt cozy with the fireplace and soft blankets.",
    transcription: "[ˈkoʊzi]",
    synonyms: ["snug", "comfortable", "homely", "warm"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "lantern",
    translation: "фонарь",
    definition: "A portable lamp with a protective case for the light source",
    example: "We carried a lantern to light our way through the dark forest path.",
    transcription: "[ˈlæntərn]",
    synonyms: ["lamp", "torch", "light"],
    topic: "daily-life",
    rarity: "rare",
  },
];

const intermediateWords: WordEntry[] = [
  {
    word: "appetite",
    translation: "аппетит",
    definition: "A natural desire to satisfy a bodily need, especially for food",
    example: "After the long hike, we all had a healthy appetite.",
    transcription: "[ˈæpɪtaɪt]",
    synonyms: ["hunger", "craving", "desire"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "recipe",
    translation: "рецепт",
    definition: "A set of instructions for preparing a particular dish",
    example: "My grandmother gave me her secret recipe for apple pie.",
    transcription: "[ˈresɪpi]",
    synonyms: ["formula", "instructions", "method"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "flavorsome",
    translation: "ароматный",
    definition: "Having a pleasant and distinctive taste",
    example: "The chef prepared a flavorsome curry with fresh spices.",
    transcription: "[ˈfleɪvərsəm]",
    synonyms: ["tasty", "savory", "palatable", "delicious"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "nutritious",
    translation: "питательный",
    definition: "Containing substances that your body needs to stay healthy",
    example: "A nutritious breakfast gives you energy for the whole day.",
    transcription: "[njuːˈtrɪʃəs]",
    synonyms: ["nourishing", "wholesome", "healthy", "beneficial"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "cuisine",
    translation: "кухня",
    definition: "A style or method of cooking, especially characteristic of a particular country or region",
    example: "Italian cuisine is famous for its pasta and pizza.",
    transcription: "[kwɪˈziːn]",
    synonyms: ["cookery", "gastronomy", "cooking style"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "ingredient",
    translation: "ингредиент",
    definition: "Any of the foods or substances combined to make a particular dish",
    example: "Fresh ingredients are the secret to a great meal.",
    transcription: "[ɪnˈɡriːdiənt]",
    synonyms: ["component", "element", "constituent"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "beverage",
    translation: "напиток",
    definition: "Any type of drink except water",
    example: "Would you like a hot or cold beverage?",
    transcription: "[ˈbevərɪdʒ]",
    synonyms: ["drink", "refreshment", "liquid"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "leftovers",
    translation: "остатки еды",
    definition: "Food remaining after a meal that is saved for later use",
    example: "We ate the leftovers from dinner for lunch the next day.",
    transcription: "[ˈleftoʊvərz]",
    synonyms: ["remains", "scraps", "surplus food"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "ripe",
    translation: "спелый",
    definition: "Fully grown and ready to be eaten, especially of fruit and grain",
    example: "The bananas are not yet ripe enough to eat.",
    transcription: "[raɪp]",
    synonyms: ["mature", "ready", "full-grown"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "banquet",
    translation: "банкет",
    definition: "A large formal meal for many people, often celebrating a special occasion",
    example: "The wedding banquet featured a five-course meal.",
    transcription: "[ˈbæŋkwɪt]",
    synonyms: ["feast", "dinner party", "gala"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "destination",
    translation: "место назначения",
    definition: "The place that someone or something is going to",
    example: "Our destination was a small island in the Mediterranean.",
    transcription: "[ˌdestɪˈneɪʃən]",
    synonyms: ["goal", "target", "endpoint", "terminus"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "itinerary",
    translation: "маршрут",
    definition: "A detailed plan or route of a journey",
    example: "The travel agent prepared a detailed itinerary for our trip.",
    transcription: "[aɪˈtɪnəreri]",
    synonyms: ["schedule", "route", "plan", "agenda"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "boarding",
    translation: "посадка",
    definition: "The act of getting on a ship, aircraft, train, or bus",
    example: "Boarding for flight 302 will begin in ten minutes.",
    transcription: "[ˈbɔːrdɪŋ]",
    synonyms: ["embarkation", "entry", "mounting"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "luggage",
    translation: "багаж",
    definition: "The bags, suitcases, and other containers that a traveller carries",
    example: "All luggage must be checked before boarding the plane.",
    transcription: "[ˈlʌɡɪdʒ]",
    synonyms: ["baggage", "bags", "belongings", "suitcases"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "departure",
    translation: "отправление",
    definition: "The act of leaving, especially to start a journey",
    example: "The departure of the train was delayed by thirty minutes.",
    transcription: "[dɪˈpɑːrtʃər]",
    synonyms: ["leaving", "exit", "takeoff", "outset"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "accommodation",
    translation: "жильё",
    definition: "A place where travellers can stay, sleep, and live temporarily",
    example: "We booked accommodation near the city center.",
    transcription: "[əˌkɒməˈdeɪʃən]",
    synonyms: ["lodging", "housing", "shelter", "residence"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "sightseeing",
    translation: "осмотр достопримечательностей",
    definition: "The activity of visiting interesting places, especially as a tourist",
    example: "We spent the afternoon sightseeing around the old town.",
    transcription: "[ˈsaɪtsiːɪŋ]",
    synonyms: ["touring", "exploring", "visiting"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "customs",
    translation: "таможня",
    definition: "The place at an airport or border where officials check goods and luggage",
    example: "You must declare any items over the limit at customs.",
    transcription: "[ˈkʌstəmz]",
    synonyms: ["border control", "immigration checkpoint"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "jetlag",
    translation: "смена часовых поясов",
    definition: "Tiredness and confusion caused by travelling between time zones",
    example: "I suffered from jetlag for the first two days after the long flight.",
    transcription: "[ˈdʒetlæɡ]",
    synonyms: ["time zone fatigue", "travel fatigue", "desynchronosis"],
    topic: "travel",
    rarity: "uncommon",
  },
  {
    word: "browser",
    translation: "браузер",
    definition: "A computer program used to access and view websites on the internet",
    example: "Make sure your browser is updated to the latest version.",
    transcription: "[ˈbraʊzər]",
    synonyms: ["web browser", "navigator"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "download",
    translation: "скачивать",
    definition: "To copy data from a larger system to your own computer or device",
    example: "You can download the app from the official store.",
    transcription: "[ˈdaʊnloʊd]",
    synonyms: ["transfer", "copy", "fetch"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "software",
    translation: "программное обеспечение",
    definition: "The programs and operating information used by a computer",
    example: "We need to install new software on all office computers.",
    transcription: "[ˈsɒftweər]",
    synonyms: ["programs", "applications", "code"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "device",
    translation: "устройство",
    definition: "A piece of equipment made for a particular purpose, especially electronic",
    example: "This device can measure your heart rate during exercise.",
    transcription: "[dɪˈvaɪs]",
    synonyms: ["gadget", "apparatus", "tool", "instrument"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "password",
    translation: "пароль",
    definition: "A secret word or phrase used to verify a user's identity",
    example: "You should use a strong password to protect your account.",
    transcription: "[ˈpæswɜːrd]",
    synonyms: ["passcode", "PIN", "key"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "network",
    translation: "сеть",
    definition: "A system of computers and other devices connected together to share information",
    example: "The office network went down for an hour this morning.",
    transcription: "[ˈnetwɜːrk]",
    synonyms: ["system", "web", "grid", "infrastructure"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "charger",
    translation: "зарядное устройство",
    definition: "A device used to put electricity into a battery",
    example: "I forgot my phone charger at home.",
    transcription: "[ˈtʃɑːrdʒər]",
    synonyms: ["power adapter", "recharger", "power supply"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "wireless",
    translation: "беспроводной",
    definition: "Using radio signals instead of wires to send and receive data",
    example: "The hotel offers free wireless internet in all rooms.",
    transcription: "[ˈwaɪərləs]",
    synonyms: ["cordless", "radio", "Wi-Fi"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "database",
    translation: "база данных",
    definition: "A structured set of data held in a computer, accessible in various ways",
    example: "All customer records are stored in our database.",
    transcription: "[ˈdeɪtəbeɪs]",
    synonyms: ["data store", "repository", "archive"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "anxious",
    translation: "тревожный",
    definition: "Worried and nervous about something that might happen or has happened",
    example: "She felt anxious before her job interview.",
    transcription: "[ˈæŋkʃəs]",
    synonyms: ["worried", "nervous", "uneasy", "apprehensive"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "grateful",
    translation: "благодарный",
    definition: "Feeling or showing thanks for something helpful or kind",
    example: "I'm deeply grateful for all your support during this difficult time.",
    transcription: "[ˈɡreɪtfəl]",
    synonyms: ["thankful", "appreciative", "indebted", "obliged"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "jealous",
    translation: "ревнивый",
    definition: "Feeling angry or unhappy because someone has something you want",
    example: "He felt jealous when his colleague got the promotion.",
    transcription: "[ˈdʒeləs]",
    synonyms: ["envious", "covetous", "resentful", "bitter"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "relieved",
    translation: "испытывающий облегчение",
    definition: "Feeling happy that something unpleasant has not happened or has ended",
    example: "I was relieved to hear that everyone was safe after the storm.",
    transcription: "[rɪˈliːvd]",
    synonyms: ["reassured", "comforted", "calmed"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "embarrassed",
    translation: "смущённый",
    definition: "Feeling ashamed or shy because of something you did or what happened",
    example: "He felt embarrassed when he tripped in front of everyone.",
    transcription: "[ɪmˈbærəst]",
    synonyms: ["ashamed", "awkward", "self-conscious", "humiliated"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "frustrated",
    translation: "разочарованный",
    definition: "Feeling annoyed and impatient because you cannot achieve what you want",
    example: "She became frustrated after trying to fix the computer for hours.",
    transcription: "[frʌˈstreɪtɪd]",
    synonyms: ["annoyed", "irritated", "exasperated", "discouraged"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "confident",
    translation: "уверенный",
    definition: "Having a strong belief in your own abilities and judgment",
    example: "She felt confident about passing the driving test.",
    transcription: "[ˈkɒnfɪdənt]",
    synonyms: ["self-assured", "sure", "poised", "bold"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "lonely",
    translation: "одинокий",
    definition: "Sad because you are not with other people and have no one to talk to",
    example: "He felt lonely after moving to a new city where he knew no one.",
    transcription: "[ˈloʊnli]",
    synonyms: ["isolated", "solitary", "forlorn", "lonesome"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "nostalgic",
    translation: "ностальгический",
    definition: "Feeling a mixture of happiness and sadness when thinking about the past",
    example: "Listening to old songs made her feel nostalgic for her childhood.",
    transcription: "[nɒˈstældʒɪk]",
    synonyms: ["wistful", "sentimental", "reminiscent", "yearning"],
    topic: "emotions",
    rarity: "uncommon",
  },
  {
    word: "negotiate",
    translation: "вести переговоры",
    definition: "To try to reach an agreement through formal discussion",
    example: "The union will negotiate with management for better working conditions.",
    transcription: "[nɪˈɡoʊʃieɪt]",
    synonyms: ["bargain", "discuss", "broker", "mediate"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "budget",
    translation: "бюджет",
    definition: "A plan of how much money you will spend on different things over a period",
    example: "We need to stay within our budget for this project.",
    transcription: "[ˈbʌdʒɪt]",
    synonyms: ["financial plan", "estimate", "allowance"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "invoice",
    translation: "счёт-фактура",
    definition: "A document showing a list of goods provided or work done and their prices",
    example: "Please send the invoice by the end of the month.",
    transcription: "[ˈɪnvɔɪs]",
    synonyms: ["bill", "statement", "receipt", "account"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "colleague",
    translation: "коллега",
    definition: "A person you work with in a job or profession",
    example: "I discussed the project with my colleagues during the meeting.",
    transcription: "[ˈkɒliːɡ]",
    synonyms: ["coworker", "associate", "teammate", "partner"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "deadline",
    translation: "крайний срок",
    definition: "The latest time or date by which something must be completed",
    example: "We are working hard to meet the Friday deadline.",
    transcription: "[ˈdedlaɪn]",
    synonyms: ["due date", "time limit", "cutoff", "target date"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "salary",
    translation: "зарплата",
    definition: "A fixed regular payment, usually paid monthly, for work done",
    example: "She received a significant increase in her salary after the promotion.",
    transcription: "[ˈsæləri]",
    synonyms: ["wages", "income", "earnings", "pay"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "invest",
    translation: "инвестировать",
    definition: "To put money into something to make a profit or get an advantage",
    example: "They decided to invest in the new startup company.",
    transcription: "[ɪnˈvest]",
    synonyms: ["finance", "fund", "back", "stake"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "contract",
    translation: "контракт",
    definition: "A legal written agreement between people or organizations",
    example: "Both parties must sign the contract before work can begin.",
    transcription: "[ˈkɒntrækt]",
    synonyms: ["agreement", "deal", "treaty", "pact"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "profit",
    translation: "прибыль",
    definition: "Money that you gain from a business after paying all the costs",
    example: "The company reported higher profits this quarter.",
    transcription: "[ˈprɒfɪt]",
    synonyms: ["earnings", "gain", "return", "surplus"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "allergy",
    translation: "аллергия",
    definition: "A medical condition that makes you ill when you eat, breathe, or touch something",
    example: "She has a severe allergy to peanuts.",
    transcription: "[ˈælərdʒi]",
    synonyms: ["sensitivity", "reaction", "intolerance", "hypersensitivity"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "symptom",
    translation: "симптом",
    definition: "A physical or mental sign of an illness or medical condition",
    example: "A sore throat is a common symptom of a cold.",
    transcription: "[ˈsɪmptəm]",
    synonyms: ["sign", "indication", "manifestation", "warning"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "prescription",
    translation: "рецепт",
    definition: "A written instruction from a doctor for medicine or treatment",
    example: "The doctor gave me a prescription for antibiotics.",
    transcription: "[prɪˈskrɪpʃən]",
    synonyms: ["Rx", "doctor's order", "medical order"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "vaccine",
    translation: "вакцина",
    definition: "A substance injected into the body to protect against a disease",
    example: "Scientists developed a new vaccine against the virus.",
    transcription: "[ˈvæksiːn]",
    synonyms: ["inoculation", "immunization", "shot", "jab"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "insomnia",
    translation: "бессонница",
    definition: "The condition of being unable to sleep over a period of time",
    example: "Stress at work caused her to suffer from insomnia.",
    transcription: "[ɪnˈsɒmniə]",
    synonyms: ["sleeplessness", "wakefulness", "restlessness"],
    topic: "health",
    rarity: "uncommon",
  },
  {
    word: "therapy",
    translation: "терапия",
    definition: "Treatment intended to relieve or heal a disorder",
    example: "She has been attending physical therapy for her back injury.",
    transcription: "[ˈθerəpi]",
    synonyms: ["treatment", "rehabilitation", "healing", "remedy"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "nutrition",
    translation: "питание",
    definition: "The process of providing the food necessary for health and growth",
    example: "Good nutrition is essential during pregnancy.",
    transcription: "[njuːˈtrɪʃən]",
    synonyms: ["nourishment", "diet", "sustenance", "food"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "diagnosis",
    translation: "диагноз",
    definition: "The identification of the nature of an illness by examination",
    example: "The doctor made a diagnosis after reviewing the test results.",
    transcription: "[ˌdaɪəɡˈnoʊsɪs]",
    synonyms: ["identification", "determination", "finding", "assessment"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "chronic",
    translation: "хронический",
    definition: "Persisting for a long time or constantly recurring",
    example: "He suffers from chronic back pain that has lasted for years.",
    transcription: "[ˈkrɒnɪk]",
    synonyms: ["persistent", "long-term", "constant", "lingering"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "semester",
    translation: "семестр",
    definition: "One of the two periods into which the academic year is divided",
    example: "She is taking five courses this semester.",
    transcription: "[sɪˈmestər]",
    synonyms: ["term", "academic period", "session"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "scholarship",
    translation: "стипендия",
    definition: "An amount of money given to a student to help pay for their education",
    example: "He received a full scholarship to study at the university.",
    transcription: "[ˈskɒlərʃɪp]",
    synonyms: ["grant", "bursary", "award", "funding"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "curriculum",
    translation: "учебная программа",
    definition: "The subjects that make up a course of study in a school or college",
    example: "The school is updating its curriculum to include digital skills.",
    transcription: "[kəˈrɪkjʊləm]",
    synonyms: ["syllabus", "program", "course of study"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "lecture",
    translation: "лекция",
    definition: "A formal talk on an academic subject given to a group of students",
    example: "The professor delivered an engaging lecture on ancient history.",
    transcription: "[ˈlektʃər]",
    synonyms: ["talk", "presentation", "address", "discourse"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "assignment",
    translation: "задание",
    definition: "A task or piece of work given to a student as part of their course",
    example: "The science assignment is due next Monday.",
    transcription: "[əˈsaɪnmənt]",
    synonyms: ["task", "project", "homework", "exercise"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "degree",
    translation: "степень",
    definition: "A qualification given by a university after completing a course of study",
    example: "She earned a degree in computer science.",
    transcription: "[dɪˈɡriː]",
    synonyms: ["qualification", "diploma", "credential"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "lecturer",
    translation: "преподаватель",
    definition: "A teacher at a university or college",
    example: "The lecturer answered questions after the class.",
    transcription: "[ˈlektʃərər]",
    synonyms: ["professor", "instructor", "academic", "educator"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "research",
    translation: "исследование",
    definition: "A careful study of a subject to discover new facts or information",
    example: "The university is funding research into renewable energy.",
    transcription: "[rɪˈsɜːrtʃ]",
    synonyms: ["study", "investigation", "exploration", "inquiry"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "knowledge",
    translation: "знания",
    definition: "Information, understanding, and skills gained through education and experience",
    example: "His knowledge of world history is impressive.",
    transcription: "[ˈnɒlɪdʒ]",
    synonyms: ["understanding", "wisdom", "expertise", "learning"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "climate",
    translation: "климат",
    definition: "The typical weather conditions in a particular area over a long period",
    example: "The Mediterranean climate is warm and sunny most of the year.",
    transcription: "[ˈklaɪmət]",
    synonyms: ["weather pattern", "atmospheric conditions", "environment"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "earthquake",
    translation: "землетрясение",
    definition: "A sudden violent shaking of the ground, causing great destruction",
    example: "The earthquake measured 7.2 on the Richter scale.",
    transcription: "[ˈɜːrθkweɪk]",
    synonyms: ["tremor", "seismic event", "quake", "shock"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "species",
    translation: "вид",
    definition: "A group of living organisms consisting of similar individuals",
    example: "Many species are at risk of extinction due to habitat loss.",
    transcription: "[ˈspiːʃiːz]",
    synonyms: ["type", "breed", "kind", "variety"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "wildlife",
    translation: "дикая природа",
    definition: "Animals, birds, and plants living in their natural environment",
    example: "The national park is home to diverse wildlife.",
    transcription: "[ˈwaɪldlaɪf]",
    synonyms: ["fauna", "animals", "creatures"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "flood",
    translation: "наводнение",
    definition: "An overflow of water that covers land that is usually dry",
    example: "Heavy rains caused severe flooding in the valley.",
    transcription: "[flʌd]",
    synonyms: ["deluge", "inundation", "overflow", "torrent"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "landscape",
    translation: "пейзаж",
    definition: "The visible features of an area of land, including natural and built elements",
    example: "The landscape of the Scottish Highlands is breathtaking.",
    transcription: "[ˈlændskeɪp]",
    synonyms: ["scenery", "view", "terrain", "panorama"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "harvest",
    translation: "урожай",
    definition: "The process or period of gathering crops from the fields",
    example: "The farmers celebrate a good harvest every autumn.",
    transcription: "[ˈhɑːrvɪst]",
    synonyms: ["reaping", "gathering", "yield", "crop"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "erosion",
    translation: "эрозия",
    definition: "The gradual wearing away of land by water, wind, or other natural agents",
    example: "Coastal erosion is threatening several villages along the shore.",
    transcription: "[ɪˈroʊʒən]",
    synonyms: ["wearing away", "deterioration", "corrosion", "degradation"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "breeze",
    translation: "ветерок",
    definition: "A gentle and pleasant wind",
    example: "A cool breeze came from the ocean on a hot summer afternoon.",
    transcription: "[briːz]",
    synonyms: ["gust", "zephyr", "draft", "wind"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "routine",
    translation: "распорядок",
    definition: "A usual pattern of activities done regularly in the same order",
    example: "My morning routine includes stretching and a cup of coffee.",
    transcription: "[ruːˈtiːn]",
    synonyms: ["habit", "schedule", "regimen", "pattern"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "appliance",
    translation: "бытовая техника",
    definition: "A device or machine used in the home to perform a specific task",
    example: "Modern kitchen appliances make cooking much easier.",
    transcription: "[əˈplaɪəns]",
    synonyms: ["device", "gadget", "machine", "tool"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "chores",
    translation: "домашние дела",
    definition: "Regular tasks done at home, such as cleaning and washing",
    example: "We split the household chores between everyone in the family.",
    transcription: "[tʃɔːrz]",
    synonyms: ["housework", "tasks", "duties", "errands"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "commute",
    translation: "поездка на работу",
    definition: "The regular journey between home and work or school",
    example: "His daily commute takes about forty-five minutes by train.",
    transcription: "[kəˈmjuːt]",
    synonyms: ["journey", "travel", "trip", "drive"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "grocery",
    translation: "продуктовый",
    definition: "Relating to food and other goods sold by a grocer",
    example: "I need to do the grocery shopping this weekend.",
    transcription: "[ˈɡroʊsəri]",
    synonyms: ["food store", "market", "supermarket items"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "laundry",
    translation: "стирка",
    definition: "Clothes and linens that need to be washed or have just been washed",
    example: "There's a pile of laundry waiting to be folded.",
    transcription: "[ˈlɔːndri]",
    synonyms: ["washing", "wash", "dirty clothes"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "furniture",
    translation: "мебель",
    definition: "Large movable objects such as chairs, tables, and beds used in a room",
    example: "We bought new furniture for the living room.",
    transcription: "[ˈfɜːrnɪtʃər]",
    synonyms: ["furnishings", "household items", "fixtures"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "schedule",
    translation: "расписание",
    definition: "A plan showing when events or activities will take place",
    example: "I have a very busy schedule today with back-to-back meetings.",
    transcription: "[ˈʃedjuːl]",
    synonyms: ["timetable", "agenda", "calendar", "plan"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "neighbour",
    translation: "сосед",
    definition: "A person living next door or very near to you",
    example: "Our neighbours invited us over for a barbecue.",
    transcription: "[ˈneɪbər]",
    synonyms: ["next-door", "local resident", "fellow resident"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "receipt",
    translation: "чек",
    definition: "A piece of paper showing that money has been paid for goods or services",
    example: "Always keep the receipt in case you need to return the item.",
    transcription: "[rɪˈsiːt]",
    synonyms: ["proof of purchase", "bill", "sales slip", "voucher"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "keepsake",
    translation: "сувенир на память",
    definition: "A small item kept in memory of the person who gave it or originally owned it",
    example: "She kept the locket as a keepsake from her grandmother.",
    transcription: "[ˈkiːpseɪk]",
    synonyms: ["memento", "souvenir", "token", "heirloom"],
    topic: "daily-life",
    rarity: "rare",
  },
  {
    word: "pastime",
    translation: "времяпрепровождение",
    definition: "An activity done regularly for enjoyment rather than work",
    example: "Birdwatching became his favorite pastime after retirement.",
    transcription: "[ˈpæstaɪm]",
    synonyms: ["hobby", "recreation", "diversion", "pursuit"],
    topic: "daily-life",
    rarity: "uncommon",
  },
];

const advancedWords: WordEntry[] = [
  {
    word: "gastronomic",
    translation: "гастрономический",
    definition: "Relating to the practice of choosing, cooking, and eating good food",
    example: "The city is renowned for its gastronomic excellence and Michelin-starred restaurants.",
    transcription: "[ˌɡæstrəˈnɒmɪk]",
    synonyms: ["culinary", "epicurean", "gourmet"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "savory",
    translation: "пикантный",
    definition: "Having a pleasant taste that is not sweet, often salty or spicy",
    example: "The chef prepared a savory dish with roasted vegetables and herbs.",
    transcription: "[ˈseɪvəri]",
    synonyms: ["piquant", "tasty", "flavorful", "appetizing"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "delectable",
    translation: "восхитительный",
    definition: "Extremely delicious and pleasing to the taste",
    example: "The chocolate soufflé was absolutely delectable.",
    transcription: "[dɪˈlektəbəl]",
    synonyms: ["delicious", "exquisite", "scrumptious", "mouthwatering"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "succulent",
    translation: "сочный",
    definition: "Tender, juicy, and full of flavor, typically used for food",
    example: "The steak was perfectly grilled and wonderfully succulent.",
    transcription: "[ˈsʌkjʊlənt]",
    synonyms: ["juicy", "tender", "moist", "luscious"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "ambrosial",
    translation: "амброзийный",
    definition: "Exceptionally pleasing to taste or smell, like the food of the gods",
    example: "The ambrosial aroma of freshly baked bread filled the bakery.",
    transcription: "[æmˈbroʊziəl]",
    synonyms: ["divine", "heavenly", "exquisite", "celestial"],
    topic: "food",
    rarity: "rare",
  },
  {
    word: "palatable",
    translation: "приемлемый на вкус",
    definition: "Having a pleasant or acceptable taste",
    example: "The doctor recommended a diet that was both nutritious and palatable.",
    transcription: "[ˈpælətəbəl]",
    synonyms: ["tasty", "agreeable", "acceptable", "sapid"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "fermentation",
    translation: "ферментация",
    definition: "The chemical breakdown of a substance by bacteria, yeast, or other microorganisms",
    example: "Fermentation is essential in the production of bread, cheese, and wine.",
    transcription: "[ˌfɜːrmenˈteɪʃən]",
    synonyms: ["brewing", "culturing", "leavening"],
    topic: "food",
    rarity: "uncommon",
  },
  {
    word: "garnish",
    translation: "гарнир",
    definition: "A decorative or flavorful addition to a dish of food",
    example: "The chef added a sprig of parsley as a garnish to the plate.",
    transcription: "[ˈɡɑːrnɪʃ]",
    synonyms: ["embellishment", "decoration", "trimming"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "culinary",
    translation: "кулинарный",
    definition: "Relating to cooking or the preparation of food",
    example: "She honed her culinary skills at a prestigious cooking school in Paris.",
    transcription: "[ˈkʌlɪneri]",
    synonyms: ["cooking", "gastronomic", "epicurean"],
    topic: "food",
    rarity: "common",
  },
  {
    word: "itinerant",
    translation: "странствующий",
    definition: "Traveling from place to place, especially for work or a regular purpose",
    example: "Itinerant merchants once traveled across continents selling their goods.",
    transcription: "[aɪˈtɪnərənt]",
    synonyms: ["nomadic", "wandering", "roving", "peripatetic"],
    topic: "travel",
    rarity: "uncommon",
  },
  {
    word: "sojourn",
    translation: "временное пребывание",
    definition: "A temporary stay in a place away from home",
    example: "Our brief sojourn in the countryside was incredibly refreshing.",
    transcription: "[ˈsɒdʒɜːrn]",
    synonyms: ["stay", "visit", "stopover", "respite"],
    topic: "travel",
    rarity: "uncommon",
  },
  {
    word: "cosmopolitan",
    translation: "космополитичный",
    definition: "Containing people and influences from many different countries",
    example: "London is one of the most cosmopolitan cities in the world.",
    transcription: "[ˌkɒzməˈpɒlɪtən]",
    synonyms: ["multicultural", "international", "diverse", "worldly"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "odyssey",
    translation: "одиссея",
    definition: "A long and eventful journey with many adventures and experiences",
    example: "Their backpacking trip across South America turned into an unforgettable odyssey.",
    transcription: "[ˈɒdɪsi]",
    synonyms: ["journey", "voyage", "expedition", "pilgrimage"],
    topic: "travel",
    rarity: "uncommon",
  },
  {
    word: "expatriate",
    translation: "экспатриант",
    definition: "A person who lives outside their native country",
    example: "She joined a community of expatriates living in Singapore.",
    transcription: "[eksˈpætriət]",
    synonyms: ["emigrant", "exile", "foreign resident", "migrant"],
    topic: "travel",
    rarity: "uncommon",
  },
  {
    word: "peregrination",
    translation: "странствие",
    definition: "A journey or travel from place to place, especially on foot",
    example: "His peregrinations across the Himalayas lasted several months.",
    transcription: "[ˌperɪɡrɪˈneɪʃən]",
    synonyms: ["wandering", "travels", "expedition", "trek"],
    topic: "travel",
    rarity: "rare",
  },
  {
    word: "nomadic",
    translation: "кочевой",
    definition: "Living the life of a nomad, moving from one place to another",
    example: "Several nomadic tribes still migrate seasonally across the plains.",
    transcription: "[noʊˈmædɪk]",
    synonyms: ["wandering", "roaming", "migratory", "itinerant"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "pilgrimage",
    translation: "паломничество",
    definition: "A journey to a sacred place for religious or spiritual reasons",
    example: "Millions of people make a pilgrimage to Mecca each year.",
    transcription: "[ˈpɪlɡrɪmɪdʒ]",
    synonyms: ["religious journey", "holy trip", "spiritual trek", "hajj"],
    topic: "travel",
    rarity: "common",
  },
  {
    word: "algorithm",
    translation: "алгоритм",
    definition: "A set of rules or steps used to solve a problem or perform a computation",
    example: "The recommendation system uses a complex algorithm to suggest content.",
    transcription: "[ˈælɡərɪðəm]",
    synonyms: ["procedure", "formula", "method", "protocol"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "encryption",
    translation: "шифрование",
    definition: "The process of converting information into a secret code to prevent unauthorized access",
    example: "End-to-end encryption ensures your messages remain private and secure.",
    transcription: "[ɪnˈkrɪpʃən]",
    synonyms: ["encoding", "ciphering", "scrambling", "cryptography"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "artificial",
    translation: "искусственный",
    definition: "Made or produced by human beings rather than occurring naturally",
    example: "Artificial intelligence is transforming industries across the globe.",
    transcription: "[ˌɑːrtɪˈfɪʃəl]",
    synonyms: ["synthetic", "man-made", "simulated", "contrived"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "bandwidth",
    translation: "пропускная способность",
    definition: "The maximum amount of data that can be transmitted over a connection in a given time",
    example: "Video streaming requires significant bandwidth for high quality.",
    transcription: "[ˈbændwɪdθ]",
    synonyms: ["capacity", "throughput", "data rate"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "obsolete",
    translation: "устаревший",
    definition: "No longer produced or used; out of date",
    example: "Floppy disks have become entirely obsolete in modern computing.",
    transcription: "[ˌɒbsəˈliːt]",
    synonyms: ["outdated", "antiquated", "defunct", "archaic"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "prototype",
    translation: "прототип",
    definition: "A first or preliminary version of a device or system from which other forms are developed",
    example: "The engineering team built a working prototype in just three months.",
    transcription: "[ˈproʊtətaɪp]",
    synonyms: ["model", "sample", "mockup", "archetype"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "ubiquitous",
    translation: "вездесущий",
    definition: "Present, appearing, or found everywhere",
    example: "Smartphones have become ubiquitous in modern society.",
    transcription: "[juːˈbɪkwɪtəs]",
    synonyms: ["omnipresent", "pervasive", "universal", "everywhere"],
    topic: "technology",
    rarity: "uncommon",
  },
  {
    word: "cybersecurity",
    translation: "кибербезопасность",
    definition: "The practice of protecting systems, networks, and programs from digital attacks",
    example: "Companies are investing heavily in cybersecurity to prevent data breaches.",
    transcription: "[ˌsaɪbərsɪˈkjʊərəti]",
    synonyms: ["digital security", "IT security", "cyber defense", "online safety"],
    topic: "technology",
    rarity: "common",
  },
  {
    word: "euphoria",
    translation: "эйфория",
    definition: "An intense feeling of happiness, excitement, and well-being",
    example: "Winning the championship sent waves of euphoria through the entire team.",
    transcription: "[juːˈfɔːriə]",
    synonyms: ["elation", "ecstasy", "rapture", "bliss"],
    topic: "emotions",
    rarity: "uncommon",
  },
  {
    word: "melancholy",
    translation: "меланхолия",
    definition: "A deep, persistent sadness or depression, often without an obvious cause",
    example: "A feeling of melancholy washed over her as the autumn leaves fell.",
    transcription: "[ˈmelənkɒli]",
    synonyms: ["sorrow", "despondency", "gloom", "wistfulness"],
    topic: "emotions",
    rarity: "uncommon",
  },
  {
    word: "indignation",
    translation: "негодование",
    definition: "Strong anger caused by something that is unfair, mean, or wrong",
    example: "The decision to close the community center was met with public indignation.",
    transcription: "[ˌɪndɪɡˈneɪʃən]",
    synonyms: ["outrage", "resentment", "fury", "righteous anger"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "apprehension",
    translation: "опасение",
    definition: "Anxious or fearful feeling about the future or something uncertain",
    example: "She felt a sense of apprehension before her first public speech.",
    transcription: "[ˌæprɪˈhenʃən]",
    synonyms: ["anxiety", "dread", "unease", "trepidation"],
    topic: "emotions",
    rarity: "common",
  },
  {
    word: "exhilaration",
    translation: "восторг",
    definition: "A feeling of excitement, happiness, and vitality",
    example: "The sheer exhilaration of skydiving left him speechless.",
    transcription: "[ɪɡˌzɪləˈreɪʃən]",
    synonyms: ["thrill", "elation", "euphoria", "excitement"],
    topic: "emotions",
    rarity: "uncommon",
  },
  {
    word: "poignant",
    translation: "трогательный",
    definition: "Evoking a keen sense of sadness, sympathy, or regret",
    example: "The documentary was a poignant reminder of the struggles refugees endure.",
    transcription: "[ˈpɔɪnjənt]",
    synonyms: ["touching", "moving", "heartbreaking", "affecting"],
    topic: "emotions",
    rarity: "uncommon",
  },
  {
    word: "benevolent",
    translation: "доброжелательный",
    definition: "Well-meaning and kindly, showing generosity and goodwill",
    example: "The benevolent donor funded scholarships for dozens of underprivileged students.",
    transcription: "[bəˈnevələnt]",
    synonyms: ["kindhearted", "charitable", "compassionate", "altruistic"],
    topic: "emotions",
    rarity: "uncommon",
  },
  {
    word: "equanimity",
    translation: "невозмутимость",
    definition: "Mental calmness and composure, especially in difficult situations",
    example: "She faced the crisis with remarkable equanimity and clear thinking.",
    transcription: "[ˌiːkwəˈnɪməti]",
    synonyms: ["composure", "serenity", "poise", "sangfroid"],
    topic: "emotions",
    rarity: "rare",
  },
  {
    word: "entrepreneur",
    translation: "предприниматель",
    definition: "A person who sets up and runs a business, taking on financial risk",
    example: "The young entrepreneur launched her first startup while still in college.",
    transcription: "[ˌɒntrəprəˈnɜːr]",
    synonyms: ["businessperson", "founder", "tycoon", "industrialist"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "acquisition",
    translation: "приобретение",
    definition: "The process of buying another company or large asset",
    example: "The tech giant announced the acquisition of a promising AI startup.",
    transcription: "[ˌækwɪˈzɪʃən]",
    synonyms: ["purchase", "takeover", "buyout", "procurement"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "dividend",
    translation: "дивиденд",
    definition: "A sum of money paid regularly by a company to its shareholders out of its profits",
    example: "The company declared a quarterly dividend of fifty cents per share.",
    transcription: "[ˈdɪvɪdend]",
    synonyms: ["share", "payout", "return", "distribution"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "liability",
    translation: "обязательство",
    definition: "A legal or financial obligation or debt that a company or person owes",
    example: "The company's liabilities exceeded its assets, leading to bankruptcy.",
    transcription: "[ˌlaɪəˈbɪləti]",
    synonyms: ["debt", "obligation", "burden", "accountability"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "remuneration",
    translation: "вознаграждение",
    definition: "Payment or compensation for services rendered or work done",
    example: "The position offers attractive remuneration and comprehensive benefits.",
    transcription: "[rɪˌmjuːnəˈreɪʃən]",
    synonyms: ["compensation", "salary", "earnings", "stipend"],
    topic: "business",
    rarity: "uncommon",
  },
  {
    word: "lucrative",
    translation: "прибыльный",
    definition: "Producing a large amount of profit",
    example: "The real estate market proved to be a highly lucrative investment.",
    transcription: "[ˈluːkrətɪv]",
    synonyms: ["profitable", "gainful", "rewarding", "fruitful"],
    topic: "business",
    rarity: "common",
  },
  {
    word: "solvent",
    translation: "платёжеспособный",
    definition: "Having enough money to pay all debts",
    example: "Despite the economic downturn, the company remained solvent throughout the crisis.",
    transcription: "[ˈsɒlvənt]",
    synonyms: ["financially stable", "liquid", "in the black", "afloat"],
    topic: "business",
    rarity: "uncommon",
  },
  {
    word: "fiduciary",
    translation: "фидуциарный",
    definition: "Relating to the responsibility of managing money or property for another person",
    example: "Financial advisors have a fiduciary duty to act in their clients' best interests.",
    transcription: "[fɪˈdjuːʃiəri]",
    synonyms: ["trustee", "custodial", "financial guardian"],
    topic: "business",
    rarity: "rare",
  },
  {
    word: "conglomerate",
    translation: "конгломерат",
    definition: "A large business corporation consisting of several different companies",
    example: "The media conglomerate owns newspapers, TV stations, and streaming platforms.",
    transcription: "[kənˈɡlɒmərət]",
    synonyms: ["corporation", "syndicate", "empire", "combine"],
    topic: "business",
    rarity: "uncommon",
  },
  {
    word: "prognosis",
    translation: "прогноз",
    definition: "A forecast of the likely outcome of a medical condition or situation",
    example: "The doctor gave a positive prognosis after the successful surgery.",
    transcription: "[prɒɡˈnoʊsɪs]",
    synonyms: ["forecast", "prediction", "outlook", "projection"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "pathogen",
    translation: "патоген",
    definition: "A bacterium, virus, or other microorganism that can cause disease",
    example: "The laboratory identified the pathogen responsible for the outbreak.",
    transcription: "[ˈpæθədʒən]",
    synonyms: ["germ", "microbe", "virus", "infectious agent"],
    topic: "health",
    rarity: "uncommon",
  },
  {
    word: "epidemiology",
    translation: "эпидемиология",
    definition: "The study of how diseases spread and can be controlled in populations",
    example: "Epidemiology was crucial in tracking and containing the pandemic.",
    transcription: "[ˌepɪdiːmiˈɒlədʒi]",
    synonyms: ["disease study", "public health science", "health statistics"],
    topic: "health",
    rarity: "uncommon",
  },
  {
    word: "resilient",
    translation: "устойчивый",
    definition: "Able to recover quickly from illness, injury, or difficult conditions",
    example: "Children are often more resilient than adults give them credit for.",
    transcription: "[rɪˈzɪliənt]",
    synonyms: ["tough", "adaptable", "robust", "hardy"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "inflammation",
    translation: "воспаление",
    definition: "A localized physical condition with redness, swelling, heat, and pain",
    example: "The medication is designed to reduce inflammation in the joints.",
    transcription: "[ˌɪnfləˈmeɪʃən]",
    synonyms: ["swelling", "irritation", "redness", "soreness"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "neurotransmitter",
    translation: "нейромедиатор",
    definition: "A chemical substance that transmits nerve impulses across a synapse",
    example: "Dopamine is a neurotransmitter associated with pleasure and reward.",
    transcription: "[ˌnjʊəroʊtrænzˈmɪtər]",
    synonyms: ["chemical messenger", "signal molecule", "synaptic transmitter"],
    topic: "health",
    rarity: "rare",
  },
  {
    word: "convalescence",
    translation: "выздоровление",
    definition: "The period of gradual recovery of health and strength after illness",
    example: "She spent several weeks in convalescence after the major operation.",
    transcription: "[ˌkɒnvəˈlesəns]",
    synonyms: ["recovery", "recuperation", "rehabilitation", "healing"],
    topic: "health",
    rarity: "uncommon",
  },
  {
    word: "palliative",
    translation: "паллиативный",
    definition: "Treating the symptoms of pain without dealing with the cause of the condition",
    example: "The patient received palliative care to manage the pain and discomfort.",
    transcription: "[ˈpæliətɪv]",
    synonyms: ["soothing", "relieving", "comforting", "alleviating"],
    topic: "health",
    rarity: "uncommon",
  },
  {
    word: "exacerbate",
    translation: "усугублять",
    definition: "To make a problem, situation, or negative feeling worse",
    example: "Excessive exercise can exacerbate certain types of injuries.",
    transcription: "[ɪɡˈzæsərbeɪt]",
    synonyms: ["aggravate", "worsen", "intensify", "compound"],
    topic: "health",
    rarity: "common",
  },
  {
    word: "erudition",
    translation: "эрудиция",
    definition: "Extensive knowledge acquired from reading and studying",
    example: "The professor was admired for his deep erudition in classical literature.",
    transcription: "[ˌerʊˈdɪʃən]",
    synonyms: ["scholarship", "learning", "expertise", "wisdom"],
    topic: "education",
    rarity: "rare",
  },
  {
    word: "pedagogy",
    translation: "педагогика",
    definition: "The method and practice of teaching, especially as an academic subject",
    example: "Modern pedagogy emphasizes interactive and student-centered learning approaches.",
    transcription: "[ˈpedəɡɒdʒi]",
    synonyms: ["teaching methods", "instruction", "education theory", "didactics"],
    topic: "education",
    rarity: "uncommon",
  },
  {
    word: "dissertation",
    translation: "диссертация",
    definition: "A long essay on a particular subject, written for a university degree",
    example: "She spent three years researching and writing her doctoral dissertation.",
    transcription: "[ˌdɪsərˈteɪʃən]",
    synonyms: ["thesis", "treatise", "paper", "monograph"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "epistemology",
    translation: "эпистемология",
    definition: "The branch of philosophy that studies the nature, origin, and limits of knowledge",
    example: "The course on epistemology challenges students to question how they know what they know.",
    transcription: "[ɪˌpɪstɪˈmɒlədʒi]",
    synonyms: ["theory of knowledge", "philosophy of knowledge", "cognitive philosophy"],
    topic: "education",
    rarity: "rare",
  },
  {
    word: "didactic",
    translation: "дидактический",
    definition: "Intended to teach or convey moral instruction",
    example: "The novel had a distinctly didactic tone, aiming to educate readers about social justice.",
    transcription: "[daɪˈdæktɪk]",
    synonyms: ["educational", "instructive", "edifying", "moralistic"],
    topic: "education",
    rarity: "uncommon",
  },
  {
    word: "cognition",
    translation: "познание",
    definition: "The mental process of acquiring knowledge and understanding through thought and experience",
    example: "Sleep plays a vital role in memory and cognition.",
    transcription: "[kɒɡˈnɪʃən]",
    synonyms: ["perception", "understanding", "comprehension", "reasoning"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "elucidate",
    translation: "разъяснять",
    definition: "To make something clear and easy to understand by explaining it",
    example: "The professor took extra time to elucidate the complex theory for the students.",
    transcription: "[ɪˈluːsɪdeɪt]",
    synonyms: ["clarify", "explain", "illuminate", "explicate"],
    topic: "education",
    rarity: "uncommon",
  },
  {
    word: "prolific",
    translation: "плодовитый",
    definition: "Producing a large amount of work, ideas, or results",
    example: "She was a prolific writer, publishing over twenty novels in her lifetime.",
    transcription: "[prəˈlɪfɪk]",
    synonyms: ["productive", "fruitful", "abundant", "copious"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "syllabus",
    translation: "учебный план",
    definition: "An outline of the subjects in a course of study or teaching",
    example: "The professor distributed the syllabus on the first day of class.",
    transcription: "[ˈsɪləbəs]",
    synonyms: ["curriculum", "program", "outline", "course guide"],
    topic: "education",
    rarity: "common",
  },
  {
    word: "biodiversity",
    translation: "биоразнообразие",
    definition: "The variety of plant and animal life in a particular habitat or in the world as a whole",
    example: "The rainforest is home to incredible biodiversity that must be protected.",
    transcription: "[ˌbaɪoʊdaɪˈvɜːrsɪti]",
    synonyms: ["ecological variety", "biological diversity", "flora and fauna"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "cataclysm",
    translation: "катаклизм",
    definition: "A large-scale and violent natural event or upheaval",
    example: "Scientists believe a cataclysm wiped out the dinosaurs millions of years ago.",
    transcription: "[ˈkætəklɪzəm]",
    synonyms: ["disaster", "catastrophe", "calamity", "upheaval"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "ecosystem",
    translation: "экосистема",
    definition: "A biological community of interacting organisms and their physical environment",
    example: "Coral reefs are among the most diverse ecosystems on the planet.",
    transcription: "[ˈiːkoʊsɪstəm]",
    synonyms: ["biome", "habitat", "environment", "ecological community"],
    topic: "nature",
    rarity: "common",
  },
  {
    word: "deciduous",
    translation: "лиственный",
    definition: "Shedding its leaves annually, typically in autumn",
    example: "The deciduous forest transforms into brilliant colors every fall.",
    transcription: "[dɪˈsɪdʒuəs]",
    synonyms: ["leaf-shedding", "broadleaf", "seasonal"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "precipitous",
    translation: "обрывистый",
    definition: "Dangerously high or steep, like a cliff",
    example: "The mountain trail became increasingly precipitous as we climbed higher.",
    transcription: "[prɪˈsɪpɪtəs]",
    synonyms: ["steep", "sheer", "abrupt", "vertical"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "verdent",
    translation: "зелёный",
    definition: "Green with grass or other rich vegetation",
    example: "The verdant hills of Ireland are famous throughout the world.",
    transcription: "[ˈvɜːrdənt]",
    synonyms: ["lush", "green", "leafy", "flourishing"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "tempest",
    translation: "буря",
    definition: "A violent windstorm, often accompanied by rain, snow, or hail",
    example: "The ship was battered by a fierce tempest in the middle of the ocean.",
    transcription: "[ˈtempɪst]",
    synonyms: ["storm", "squall", "gale", "hurricane"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "geothermal",
    translation: "геотермальный",
    definition: "Relating to the heat produced inside the earth",
    example: "Iceland uses geothermal energy to heat most of its homes.",
    transcription: "[ˌdʒiːoʊˈθɜːrməl]",
    synonyms: ["volcanic", "thermal", "earth-heated"],
    topic: "nature",
    rarity: "uncommon",
  },
  {
    word: "serendipity",
    translation: "счастливая случайность",
    definition: "The occurrence of events by chance in a happy or beneficial way",
    example: "Finding that bookshop was pure serendipity; I had no idea it existed.",
    transcription: "[ˌserənˈdɪpɪti]",
    synonyms: ["luck", "chance", "fortuity", "fluke"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "meticulous",
    translation: "дотошный",
    definition: "Showing great attention to detail; very careful and precise",
    example: "She is a meticulous planner who leaves nothing to chance.",
    transcription: "[mɪˈtɪkjʊləs]",
    synonyms: ["thorough", "precise", "careful", "scrupulous"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "procrastination",
    translation: "прокрастинация",
    definition: "The action of delaying or postponing something that should be done",
    example: "Procrastination is often the biggest obstacle to achieving one's goals.",
    transcription: "[prəˌkræstɪˈneɪʃən]",
    synonyms: ["delay", "postponement", "dithering", "stalling"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "circumspect",
    translation: "осмотрительный",
    definition: "Wary and unwilling to take risks; considering all possible outcomes",
    example: "Investors have become more circumspect after last year's financial turmoil.",
    transcription: "[ˈsɜːrkəmspekt]",
    synonyms: ["cautious", "prudent", "wary", "vigilant"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "gregarious",
    translation: "общительный",
    definition: "Fond of company and enjoying being with other people",
    example: "His gregarious nature made him the center of every social gathering.",
    transcription: "[ɡrɪˈɡeəriəs]",
    synonyms: ["sociable", "outgoing", "convivial", "companionable"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "perpetual",
    translation: "вечный",
    definition: "Never ending or changing; occurring repeatedly",
    example: "The city seems to be in a state of perpetual construction.",
    transcription: "[pərˈpetʃuəl]",
    synonyms: ["constant", "endless", "unceasing", "everlasting"],
    topic: "daily-life",
    rarity: "common",
  },
  {
    word: "quintessential",
    translation: "типичный",
    definition: "Representing the most perfect or typical example of a quality or class",
    example: "This café is the quintessential Parisian bistro with its terrace and espresso.",
    transcription: "[ˌkwɪntɪˈsenʃəl]",
    synonyms: ["archetypal", "classic", "ideal", "prototypical"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "penchant",
    translation: "склонность",
    definition: "A strong habitual liking for something or tendency to do something",
    example: "She has a penchant for collecting vintage vinyl records.",
    transcription: "[ˈpentʃənt]",
    synonyms: ["fondness", "inclination", "predilection", "proclivity"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "fortuitous",
    translation: "случайный",
    definition: "Happening by accident or chance rather than design",
    example: "Their meeting was entirely fortuitous, but it changed both their lives.",
    transcription: "[fɔːrˈtjuːɪtəs]",
    synonyms: ["accidental", "unexpected", "coincidental", "serendipitous"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "magnanimous",
    translation: "великодушный",
    definition: "Very generous or forgiving, especially toward a rival or less powerful person",
    example: "In a magnanimous gesture, the winner praised his opponent's efforts.",
    transcription: "[mæɡˈnænɪməs]",
    synonyms: ["generous", "noble", "benevolent", "charitable"],
    topic: "daily-life",
    rarity: "rare",
  },
  {
    word: "ostentatious",
    translation: "показной",
    definition: "Characterized by vulgar or pretentious display designed to impress",
    example: "The billionaire's ostentatious mansion featured gold-plated fixtures and a private cinema.",
    transcription: "[ˌɒstenˈteɪʃəs]",
    synonyms: ["showy", "flamboyant", "pretentious", "gaudy"],
    topic: "daily-life",
    rarity: "uncommon",
  },
  {
    word: "ephemeral",
    translation: "эфемерный",
    definition: "Lasting for a very short time; transient and fleeting",
    example: "The beauty of cherry blossoms is ephemeral, lasting only a few days each spring.",
    transcription: "[ɪˈfemərəl]",
    synonyms: ["fleeting", "transient", "momentary", "brief"],
    topic: "nature",
    rarity: "uncommon",
  },
];

export const wordBanks: Record<Difficulty, WordEntry[]> = {
  beginner: beginnerWords,
  intermediate: intermediateWords,
  advanced: advancedWords,
};

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getWordsForDifficulty(
  difficulty: Difficulty,
  count: number = 10
): WordEntry[] {
  const words = wordBanks[difficulty] ?? wordBanks.beginner;
  const shuffled = shuffleArray(words);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function getWordsByTopic(
  difficulty: Difficulty,
  topic: string
): WordEntry[] {
  const words = wordBanks[difficulty] ?? wordBanks.beginner;
  return words.filter((word) => word.topic === topic);
}
